-- Empaque del modelo: catálogo reutilizable (1 MD_PACKAGING -> N MD_MODEL).
-- El modelo referencia su empaque vía MD_MODEL.ID_DLK_PACKING (FK nullable).
-- Aditiva: tabla nueva + columna nullable + FK. No toca datos existentes.
-- Nota: TYPE se amplía a VARCHAR(500) (el "Tipo" de la app es un texto descriptivo largo).

CREATE TABLE `MD_PACKAGING` (
  `ID_DLK_PACKING`       INT NOT NULL AUTO_INCREMENT,
  `TYPE`                 VARCHAR(500) NOT NULL,
  `WEIGHT`               DECIMAL(10,3) NULL,
  `VOLUME`               DECIMAL(10,3) NULL,
  `RECYCLING`            VARCHAR(45) NULL,
  `PERCENTAGE_RECYCLED`  DECIMAL(5,2) NULL,
  `STATE_PACKAGING`      TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`           VARCHAR(20) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`     TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_PACKING`),
  INDEX `IDX_MD_PACKAGING_RECYCLING` (`RECYCLING`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `MD_MODEL`
  ADD COLUMN `ID_DLK_PACKING` INT NULL AFTER `TECHNICAL_SPECIFICATION_FILE`,
  ADD INDEX `FK_MODEL_PACKING` (`ID_DLK_PACKING`),
  ADD CONSTRAINT `fk_model_packing`
    FOREIGN KEY (`ID_DLK_PACKING`) REFERENCES `MD_PACKAGING` (`ID_DLK_PACKING`)
    ON DELETE SET NULL ON UPDATE CASCADE;
