START TRANSACTION;

DELETE FROM MD_INPUT_ACTIVITIES;
DELETE FROM MD_OUTPUT_ACTIVITIES;
DELETE FROM MD_PROCEDURE_ACTIVITIES;
DELETE FROM MD_ACTIVITIES;

DELETE FROM MD_INPUT_SUBPROCESS;
DELETE FROM MD_OUTPUT_SUBPROCESS;
DELETE FROM MD_PROCEDURE_SUBPROCESS;
DELETE FROM MD_SUBPROCESS;

ALTER TABLE MD_INPUT_ACTIVITIES     AUTO_INCREMENT = 1;
ALTER TABLE MD_OUTPUT_ACTIVITIES    AUTO_INCREMENT = 1;
ALTER TABLE MD_PROCEDURE_ACTIVITIES AUTO_INCREMENT = 1;
ALTER TABLE MD_ACTIVITIES           AUTO_INCREMENT = 1;
ALTER TABLE MD_INPUT_SUBPROCESS     AUTO_INCREMENT = 1;
ALTER TABLE MD_OUTPUT_SUBPROCESS    AUTO_INCREMENT = 1;
ALTER TABLE MD_PROCEDURE_SUBPROCESS AUTO_INCREMENT = 1;
ALTER TABLE MD_SUBPROCESS           AUTO_INCREMENT = 1;

COMMIT;

SELECT
  (SELECT COUNT(*) FROM MD_SUBPROCESS) AS subprocesos,
  (SELECT COUNT(*) FROM MD_PROCEDURE_SUBPROCESS) AS prc_sub,
  (SELECT COUNT(*) FROM MD_INPUT_SUBPROCESS) AS inp_sub,
  (SELECT COUNT(*) FROM MD_OUTPUT_SUBPROCESS) AS out_sub,
  (SELECT COUNT(*) FROM MD_ACTIVITIES) AS actividades,
  (SELECT COUNT(*) FROM MD_PROCEDURE_ACTIVITIES) AS prc_act,
  (SELECT COUNT(*) FROM MD_INPUT_ACTIVITIES) AS inp_act,
  (SELECT COUNT(*) FROM MD_OUTPUT_ACTIVITIES) AS out_act;
