-- =====================================================================
--  FLUJO "RUTA DE PRODUCCIÓN" (por LOTE, a nivel de COMPONENTE)
--  Versión corregida — incorpora:
--    Mejora #1  IoT fuera de OD_PROCESS_ROUTE (las route son por lote)
--    Mejora #2  OD_ORDER_COMPONENT homologado al estándar de auditoría
--    Mejora #3  Nueva tabla unitaria OD_UNIT_TRACE (la "prenda que nace")
--  + bugs corregidos (índice, FK, OBSERVATION, CRITICALITY, STATE, fk_OD)
--  + cascada interna, UNIQUE de precedencia, unidades de tiempo en SEGUNDOS
--
--  Jerarquía:
--    OD_ORDER_DETAIL (set) -> OD_ORDER_COMPONENT (lote por pieza)
--      -> OD_PROCESS_ROUTE -> OD_SUBPROCESS_ROUTE -> OD_ACTIVITIES_ROUTE
--         (cada nivel con INPUT / PROCEDURE / OUTPUT)
--    OD_ORDER_LABEL_DETAIL (unidad serializada) -> OD_UNIT_TRACE (IoT)
--
--  Nota: ejecutar en orden (respeta dependencias de FK).
--  Quitar el prefijo de schema `mydb.` si la BD destino es otra.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0) OD_ORDER_COMPONENT  — explota un OD_ORDER_DETAIL (set) en sus piezas
--    Mejora #2: auditoría homologada (DATETIME(3), NOT NULL, DES_ACCION(10)),
--    charset explícito, ID_DLK_ORDER_HEAD con su FK, COD_COMPONENT indexable.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `OD_ORDER_COMPONENT` (
  `ID_DLK_ORDER_COMPONENT` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ORDER_HEAD`      INT NOT NULL,
  `ID_DLK_ORDER_DETAIL`    INT NOT NULL,
  `COD_COMPONENT`          VARCHAR(50)  NULL DEFAULT NULL,   -- ✅ código corto e indexable
  `NAME_COMPONENT`         VARCHAR(200) NULL DEFAULT NULL,   -- Ej: 'CHAQUETA MANGA LARGA', 'PANTALON'
  `STATE_ORDER_COMPONENT`  TINYINT UNSIGNED NOT NULL DEFAULT 1,

  -- Auditoría / Data Lake (homologada al estándar de las route)
  `COD_USUARIO_CARGA_DL`   VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`             VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`       TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_ORDER_COMPONENT`),

  INDEX `idx_component_head`   (`ID_DLK_ORDER_HEAD` ASC),
  INDEX `idx_component_detail` (`ID_DLK_ORDER_DETAIL` ASC),
  INDEX `idx_component_code`   (`COD_COMPONENT` ASC),

  CONSTRAINT `fk_OD_ORDER_COMPONENT_OD_ORDER_HEAD1`
    FOREIGN KEY (`ID_DLK_ORDER_HEAD`)
    REFERENCES `OD_ORDER_HEAD` (`ID_DLK_ORDER_HEAD`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,

  CONSTRAINT `fk_OD_ORDER_COMPONENT_OD_ORDER_DETAIL1`
    FOREIGN KEY (`ID_DLK_ORDER_DETAIL`)
    REFERENCES `OD_ORDER_DETAIL` (`ID_DLK_ORDER_DETAIL`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- =====================================================================
--  NIVEL 1 · PROCESO
-- =====================================================================

-- ---------------------------------------------------------------------
-- OD_PROCESS_ROUTE  (ruta por lote del componente)
--   Bug#1: índice usa la columna real ID_DLK_ORDER_COMPONENT
--   Bug#2: FK a OD_ORDER_COMPONENT añadida
--   Mejora#1: ID_ITEM_UNICO_IOT y su índice ELIMINADOS (son unitarios -> OD_UNIT_TRACE)
--   + UNIQUE de precedencia por componente
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `OD_PROCESS_ROUTE` (
  `ID_DLK_PROCESS_ROUTE`       INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ORDER_COMPONENT`     INT NOT NULL,
  `ORDEN_PRECEDENCIA_PROCESS`  SMALLINT UNSIGNED NOT NULL,
  `COD_PROCESS`                VARCHAR(50)  NOT NULL,
  `NAME_PROCESS`               VARCHAR(100) NOT NULL,
  `CRITICALITY_PROCESS`        ENUM('LOW','MEDIUM','HIGH') NOT NULL DEFAULT 'MEDIUM',
  `OUTSOURCED_PROCESS`         TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `ESTIMATED_TIME_PROCESS`     INT UNSIGNED NOT NULL DEFAULT 0,   -- ✅ en SEGUNDOS
  `RESPONSIBLE_UNIT`           VARCHAR(50) NOT NULL,
  `RESPONSIBLE_PROCESS`        VARCHAR(50) NOT NULL,
  `INPUT_TIME_PROCESS_ROUTE`   DATETIME(3) NULL DEFAULT NULL,     -- entrada del LOTE
  `OUTPUT_TIME_PROCESS_ROUTE`  DATETIME(3) NULL DEFAULT NULL,     -- salida del LOTE
  `STATE_PROCESS_ROUTE`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`       VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                 VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`           TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_PROCESS_ROUTE`),

  INDEX `idx_component_precedence` (`ID_DLK_ORDER_COMPONENT` ASC, `ORDEN_PRECEDENCIA_PROCESS` ASC),
  UNIQUE INDEX `uq_process_route_precedence` (`ID_DLK_ORDER_COMPONENT` ASC, `ORDEN_PRECEDENCIA_PROCESS` ASC),

  CONSTRAINT `fk_OD_PROCESS_ROUTE_OD_ORDER_COMPONENT1`
    FOREIGN KEY (`ID_DLK_ORDER_COMPONENT`)
    REFERENCES `OD_ORDER_COMPONENT` (`ID_DLK_ORDER_COMPONENT`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- Bug#3: OBSERVATION restaurada (estaba comentada) · FILE -> 255
CREATE TABLE IF NOT EXISTS `OD_INPUT_PROCESS_ROUTE` (
  `ID_DLK_INPUT_PROCESS_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_PROCESS_ROUTE`       INT NOT NULL,
  `COD_INPUT_PROCESS`          VARCHAR(50)  NOT NULL,
  `NAME_INPUT_PROCESS`         VARCHAR(100) NOT NULL,
  `SUPPLIER_INPUT_PROCESS`     VARCHAR(120) NULL DEFAULT NULL,
  `FILE_INPUT_PROCESS_ROUTE`   VARCHAR(255) NULL DEFAULT NULL,    -- ✅ 100 -> 255
  `OBSERVATION_INPUT_PROCESS`  VARCHAR(255) NULL DEFAULT NULL,    -- ✅ restaurada
  `STATE_INPUT_PROCESS`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`       VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                 VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`           TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_INPUT_PROCESS_ROUTE`),
  INDEX `fk_OD_INPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1_idx` (`ID_DLK_PROCESS_ROUTE` ASC),
  INDEX `idx_input_code` (`COD_INPUT_PROCESS` ASC),
  CONSTRAINT `fk_OD_INPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`)
    REFERENCES `OD_PROCESS_ROUTE` (`ID_DLK_PROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION                          -- ✅ cascada interna
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- Bug: CRITICALLY -> CRITICALITY · tiempo en SEGUNDOS · cascada
CREATE TABLE IF NOT EXISTS `OD_PROCEDURE_PROCESS_ROUTE` (
  `ID_DLK_PROCEDURE_PROCESS`     INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_PROCESS_ROUTE`         INT NOT NULL,
  `COD_PROCEDURE_PROCESS`        VARCHAR(50)  NOT NULL,
  `NAME_PROCEDURE_PROCESS`       VARCHAR(150) NOT NULL,
  `CRITICALITY_PROCEDURE_PROCESS` ENUM('LOW','MEDIUM','HIGH') NOT NULL DEFAULT 'MEDIUM',  -- ✅ typo corregido
  `TIME_PROCEDURE_PROCESS_ROUTE` INT UNSIGNED NOT NULL DEFAULT 0,  -- ✅ en SEGUNDOS (antes minutos)
  `VALIDATION_PROCEDURE_PROCESS` VARCHAR(255) NOT NULL,
  `FILE_PROCEDURE_PROCESS`       VARCHAR(255) NULL DEFAULT NULL,
  `STATE_PROCEDURE_PROCESS`      TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`         VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                   VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`             TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_PROCEDURE_PROCESS`),
  INDEX `fk_OD_PROCEDURE_PROCESS_ROUTE_idx` (`ID_DLK_PROCESS_ROUTE` ASC),
  INDEX `idx_procedure_code` (`COD_PROCEDURE_PROCESS` ASC),
  CONSTRAINT `fk_OD_PROCEDURE_PROCESS_OD_PROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`)
    REFERENCES `OD_PROCESS_ROUTE` (`ID_DLK_PROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- Bug: constraint fk_MD_ -> fk_OD_ · cascada
CREATE TABLE IF NOT EXISTS `OD_OUTPUT_PROCESS_ROUTE` (
  `ID_DLK_OUTPUT_PROCESS`       INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_PROCESS_ROUTE`        INT NOT NULL,
  `COD_OUTPUT_PROCESS`          VARCHAR(50)  NOT NULL,
  `NAME_OUTPUT_PROCESS`         VARCHAR(150) NOT NULL,
  `TYPE_OUTPUT_PROCESS`         VARCHAR(50)  NOT NULL,
  `DESTINATION_OUTPUT_PROCESS`  VARCHAR(100) NOT NULL,
  `UNIT_QUANTITY`               DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 1.00,
  `STATE_OUTPUT_PROCESS`        TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `FILE_OUTPUT_PROCESS_ROUTE`   VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVATION_OUTPUT_PROCESS`  VARCHAR(255) NULL DEFAULT NULL,

  `COD_USUARIO_CARGA_DL`        VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                  VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`            TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_OUTPUT_PROCESS`),
  INDEX `fk_OD_OUTPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1_idx` (`ID_DLK_PROCESS_ROUTE` ASC),
  INDEX `idx_output_code` (`COD_OUTPUT_PROCESS` ASC),
  CONSTRAINT `fk_OD_OUTPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1`     -- ✅ fk_MD_ -> fk_OD_
    FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`)
    REFERENCES `OD_PROCESS_ROUTE` (`ID_DLK_PROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- =====================================================================
--  NIVEL 2 · SUBPROCESO
-- =====================================================================

CREATE TABLE IF NOT EXISTS `OD_SUBPROCESS_ROUTE` (
  `ID_DLK_SUBPROCESS_ROUTE`       INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_PROCESS_ROUTE`          INT NOT NULL,
  `ORDEN_PRECEDENCIA_SUBPROCESS`  SMALLINT UNSIGNED NOT NULL,
  `COD_SUBPROCESS`                VARCHAR(20)  NOT NULL,
  `NAME_SUBPROCESS`               VARCHAR(100) NOT NULL,
  `CRITICALITY_SUBPROCESS`        ENUM('LOW','MEDIUM','HIGH') NOT NULL DEFAULT 'MEDIUM',
  `OUTSOURCED_SUBPROCESS`         TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `ESTIMATED_TIME_SUBPROCESS`     INT UNSIGNED NOT NULL DEFAULT 0,   -- en SEGUNDOS
  `RESPONSIBLE_UNIT`              VARCHAR(50) NULL DEFAULT NULL,
  `RESPONSIBLE_ROLE`              VARCHAR(50) NULL DEFAULT NULL,
  `INPUT_TIME_SUBPROCESS_ROUTE`   DATETIME(3) NULL DEFAULT NULL,
  `OUTPUT_TIME_SUBPROCESS_ROUTE`  DATETIME(3) NULL DEFAULT NULL,
  `STATE_SUBPROCESS`              TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`          VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                    VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`              TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_SUBPROCESS_ROUTE`),
  INDEX `fk_OD_SUBPROCESS_ROUTE_OD_PROCESS_ROUTE1_idx` (`ID_DLK_PROCESS_ROUTE` ASC, `ORDEN_PRECEDENCIA_SUBPROCESS` ASC),
  INDEX `idx_subprocess_code` (`COD_SUBPROCESS` ASC),
  UNIQUE INDEX `uq_subprocess_route_precedence` (`ID_DLK_PROCESS_ROUTE` ASC, `ORDEN_PRECEDENCIA_SUBPROCESS` ASC),
  CONSTRAINT `fk_OD_SUBPROCESS_ROUTE_OD_PROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`)
    REFERENCES `OD_PROCESS_ROUTE` (`ID_DLK_PROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `OD_INPUT_SUBPROCESS_ROUTE` (
  `ID_DLK_INPUT_SUBPROCESS_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_SUBPROCESS_ROUTE`       INT NOT NULL,
  `COD_INPUT_SUBPROCESS`          VARCHAR(50)  NOT NULL,
  `NAME_INPUT_SUBPROCESS`         VARCHAR(150) NOT NULL,
  `TYPE_INPUT_SUBPROCESS`         VARCHAR(50)  NOT NULL,
  `SUPPLIER_INPUT_SUBPROCESS`     VARCHAR(120) NULL DEFAULT NULL,
  `FILE_INPUT_SUBPROCESS`         VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVATION_INPUT_SUBPROCESS`  VARCHAR(255) NULL DEFAULT NULL,
  `STATE_INPUT_SUBPROCESS`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`          VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                    VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`              TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_INPUT_SUBPROCESS_ROUTE`),
  INDEX `fk_OD_INPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1_idx` (`ID_DLK_SUBPROCESS_ROUTE` ASC),
  INDEX `idx_input_sub_code` (`COD_INPUT_SUBPROCESS` ASC),
  CONSTRAINT `fk_OD_INPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`)
    REFERENCES `OD_SUBPROCESS_ROUTE` (`ID_DLK_SUBPROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `OD_PROCEDURE_SUBPROCESS_ROUTE` (
  `ID_DLK_PROCEDURE_SUBPROCESS_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_SUBPROCESS_ROUTE`           INT NOT NULL,
  `COD_PROCEDURE_SUBPROCESS`          VARCHAR(50)  NOT NULL,
  `NAME_PROCEDURE_SUBPROCESS`         VARCHAR(150) NOT NULL,
  `RESPONSIBLE_PROCEDURE_SUBPROCESS`  VARCHAR(100) NOT NULL,
  `ESTIMATED_TIME_PROCEDURE_SUBPROCESS` INT UNSIGNED NOT NULL DEFAULT 0,  -- en SEGUNDOS
  `CRITICALITY_PROCEDURE_SUBPROCESS`  ENUM('LOW','MEDIUM','HIGH') NOT NULL DEFAULT 'MEDIUM',
  `VALIDATION_METHOD_SUBPROCESS`      VARCHAR(255) NOT NULL,
  `FILE_PROCEDURE_SUBPROCESS`         VARCHAR(255) NULL DEFAULT NULL,
  `STATE_PROCEDURE_SUBPROCESS`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`              VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                        VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`                  TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_PROCEDURE_SUBPROCESS_ROUTE`),
  INDEX `fk_OD_PROCEDURE_SUBPROCESS_ROUTE_SUBPROCESS_idx` (`ID_DLK_SUBPROCESS_ROUTE` ASC),
  INDEX `idx_procedure_sub_code` (`COD_PROCEDURE_SUBPROCESS` ASC),
  CONSTRAINT `fk_OD_PROCEDURE_SUBPROCESS_OD_SUBPROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`)
    REFERENCES `OD_SUBPROCESS_ROUTE` (`ID_DLK_SUBPROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- Bug: STATE_OUTPUT -> STATE_OUTPUT_SUBPROCESS · fk_MD_ -> fk_OD_ · cascada
CREATE TABLE IF NOT EXISTS `OD_OUTPUT_SUBPROCESS_ROUTE` (
  `ID_DLK_OUTPUT_SUBPROCESS_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_SUBPROCESS_ROUTE`        INT NOT NULL,
  `COD_OUTPUT_SUBPROCESS`          VARCHAR(50)  NOT NULL,
  `NAME_OUTPUT_SUBPROCESS`         VARCHAR(150) NOT NULL,
  `DESTINATION_OUTPUT_SUBPROCESS`  VARCHAR(100) NOT NULL,
  `UNIT_QUANTITY`                  DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 1.00,
  `FILE_OUTPUT_SUBPROCESS_ROUTE`   VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVATION_OUTPUT_SUBPROCESS`  VARCHAR(255) NULL DEFAULT NULL,
  `STATE_OUTPUT_SUBPROCESS`        TINYINT UNSIGNED NOT NULL DEFAULT 1,   -- ✅ renombrada

  `COD_USUARIO_CARGA_DL`           VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                     VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`               TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_OUTPUT_SUBPROCESS_ROUTE`),
  INDEX `fk_OD_OUTPUT_SUBPROCESS_ROUTE_SUBPROCESS_idx` (`ID_DLK_SUBPROCESS_ROUTE` ASC),
  INDEX `idx_output_sub_code` (`COD_OUTPUT_SUBPROCESS` ASC),
  CONSTRAINT `fk_OD_OUTPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1`     -- ✅ fk_MD_ -> fk_OD_
    FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`)
    REFERENCES `OD_SUBPROCESS_ROUTE` (`ID_DLK_SUBPROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- =====================================================================
--  NIVEL 3 · ACTIVIDAD
-- =====================================================================

CREATE TABLE IF NOT EXISTS `OD_ACTIVITIES_ROUTE` (
  `ID_DLK_ACTIVITIES_ROUTE`      INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_SUBPROCESS_ROUTE`      INT NOT NULL,
  `COD_ACTIVITIES`               VARCHAR(20)  NOT NULL,
  `NAME_ACTIVITIES`              VARCHAR(150) NOT NULL,
  `TYPE_ACTIVITIES`              VARCHAR(50)  NOT NULL,
  `ORDER_ACTIVITIES`             SMALLINT UNSIGNED NOT NULL,
  `ESTIMATED_TIME_ACTIVITIES`    INT UNSIGNED NOT NULL DEFAULT 0,   -- en SEGUNDOS
  `RESPONSIBLE_NAME`             VARCHAR(100) NULL DEFAULT NULL,
  `INPUT_TIME_ACTIVITIES_ROUTE`  DATETIME(3) NULL DEFAULT NULL,
  `OUTPUT_TIME_ACTIVITIES_ROUTE` DATETIME(3) NULL DEFAULT NULL,
  `STATE_ACTIVITIES`             TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`         VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                   VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`             TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_ACTIVITIES_ROUTE`),
  INDEX `fk_OD_ACTIVITIES_ROUTE_OD_SUBPROCESS_ROUTE1_idx` (`ID_DLK_SUBPROCESS_ROUTE` ASC, `ORDER_ACTIVITIES` ASC),
  INDEX `idx_activities_code` (`COD_ACTIVITIES` ASC),
  UNIQUE INDEX `uq_activities_route_order` (`ID_DLK_SUBPROCESS_ROUTE` ASC, `ORDER_ACTIVITIES` ASC),
  CONSTRAINT `fk_OD_ACTIVITIES_ROUTE_OD_SUBPROCESS_ROUTE1`
    FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`)
    REFERENCES `OD_SUBPROCESS_ROUTE` (`ID_DLK_SUBPROCESS_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `OD_INPUT_ACTIVITIES_ROUTE` (
  `ID_DLK_INPUT_ACTIVITIES_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ACTIVITIES_ROUTE`       INT NOT NULL,
  `COD_INPUT_ACTIVITIES`          VARCHAR(50)  NOT NULL,
  `NAME_INPUT_ACTIVITIES`         VARCHAR(150) NOT NULL,
  `TYPE_INPUT_ACTIVITIES`         VARCHAR(50)  NOT NULL,
  `CRITICAL_CHECK_ACTIVITIES`     VARCHAR(150) NULL DEFAULT NULL,
  `FILE_INPUT_ACTIVITIES`         VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVATION_INPUT_ACTIVITIES`  VARCHAR(255) NULL DEFAULT NULL,
  `STATE_INPUT_ACTIVITIES`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`          VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                    VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`              TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_INPUT_ACTIVITIES_ROUTE`),
  INDEX `fk_OD_INPUT_ACTIVITIES_ROUTE_ACTIVITIES_idx` (`ID_DLK_ACTIVITIES_ROUTE` ASC),
  INDEX `idx_input_act_code` (`COD_INPUT_ACTIVITIES` ASC),
  CONSTRAINT `fk_OD_INPUT_ACTIVITIES_ROUTE_OD_ACTIVITIES_ROUTE1`
    FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`)
    REFERENCES `OD_ACTIVITIES_ROUTE` (`ID_DLK_ACTIVITIES_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `OD_PROCEDURE_ACTIVITIES_ROUTE` (
  `ID_DLK_PROCEDURE_ACTIVITIES_ROUTE` INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ACTIVITIES_ROUTE`           INT NOT NULL,
  `COD_PROCEDURE_ACTIVITIES`          VARCHAR(50)  NOT NULL,
  `NAME_PROCEDURE_ACTIVITIES`         VARCHAR(150) NOT NULL,
  `RESPONSIBLE_EXECUTION`             VARCHAR(100) NOT NULL,
  `ESTIMATED_TIME_PROCEDURE`          INT UNSIGNED NOT NULL DEFAULT 0,   -- en SEGUNDOS
  `CRITICAL_POINT_ACTIVITIES`         VARCHAR(255) NOT NULL,
  `FILE_PROCEDURE_ACTIVITIES`         VARCHAR(255) NULL DEFAULT NULL,
  `OBSERVATION_ACTIVITIES`            VARCHAR(255) NULL DEFAULT NULL,
  `STATE_PROCEDURE_ACTIVITIES`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`              VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                        VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`                  TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_PROCEDURE_ACTIVITIES_ROUTE`),
  INDEX `fk_OD_PROCEDURE_ACTIVITIES_ROUTE_ACTIVITIES_idx` (`ID_DLK_ACTIVITIES_ROUTE` ASC),
  INDEX `idx_proc_act_code` (`COD_PROCEDURE_ACTIVITIES` ASC),
  CONSTRAINT `fk_OD_PROCEDURE_ACTIVITIES_OD_ACTIVITIES_ROUTE1`
    FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`)
    REFERENCES `OD_ACTIVITIES_ROUTE` (`ID_DLK_ACTIVITIES_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `OD_OUTPUT_ACTIVITIES_ROUTE` (
  `ID_DLK_OUTPUT_ACTIVITIES`       INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ACTIVITIES_ROUTE`        INT NOT NULL,
  `COD_OUTPUT_ACTIVITIES`          VARCHAR(50)  NOT NULL,
  `NAME_OUTPUT_ACTIVITIES`         VARCHAR(150) NOT NULL,
  `TYPE_OUTPUT_ACTIVITIES`         VARCHAR(50)  NOT NULL,
  `NEXT_DESTINATION_ACTIVITIES`    VARCHAR(100) NULL DEFAULT NULL,
  `QUALITY_STANDARD_ACTIVITIES`    VARCHAR(255) NULL DEFAULT NULL,
  `FILE_OUTPUT_ACTIVITIES`         VARCHAR(255) NULL DEFAULT NULL,
  `STATE_OUTPUT_ACTIVITIES`        TINYINT UNSIGNED NOT NULL DEFAULT 1,

  `COD_USUARIO_CARGA_DL`           VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                     VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`               TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_OUTPUT_ACTIVITIES`),
  INDEX `fk_OD_OUTPUT_ACTIVITIES_ROUTE_ACTIVITIES_idx` (`ID_DLK_ACTIVITIES_ROUTE` ASC),
  INDEX `idx_output_act_code` (`COD_OUTPUT_ACTIVITIES` ASC),
  CONSTRAINT `fk_OD_OUTPUT_ACTIVITIES_OD_ACTIVITIES_ROUTE1`
    FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`)
    REFERENCES `OD_ACTIVITIES_ROUTE` (`ID_DLK_ACTIVITIES_ROUTE`)
    ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- =====================================================================
--  Mejora #3 · TRAZABILIDAD UNITARIA / IoT  (la "prenda que nace")
--  Nace al ensamblar las partes + pegar la etiqueta. La identidad de la
--  unidad es OD_ORDER_LABEL_DETAIL (SGTIN / QR / DPP ya existente).
--  Registra eventos por unidad desde el nacimiento (acabados, QC, empaque).
-- =====================================================================
CREATE TABLE IF NOT EXISTS `OD_UNIT_TRACE` (
  `ID_DLK_UNIT_TRACE`          INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_ORDER_LABEL_DETAIL`  INT NOT NULL,                 -- identidad: unidad serializada (SGTIN/QR)
  `ID_ITEM_UNICO_IOT`          VARCHAR(50) NULL DEFAULT NULL, -- chip RFID/NFC leído al nacer
  `ID_DLK_ACTIVITIES_ROUTE`    INT NULL DEFAULT NULL,        -- "dónde" (estación/actividad); SET NULL si se regenera la ruta
  `TYPE_EVENT`                 VARCHAR(50) NOT NULL,         -- Ej: 'NACIMIENTO','ACABADO','QC','EMPAQUE','DESPACHO'
  `EVENT_TIME`                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `STATE_UNIT_TRACE`           TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `OBSERVATION_UNIT_TRACE`     VARCHAR(255) NULL DEFAULT NULL,

  `COD_USUARIO_CARGA_DL`       VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`                 VARCHAR(10) NOT NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`           TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,

  PRIMARY KEY (`ID_DLK_UNIT_TRACE`),
  INDEX `idx_unit_trace_label` (`ID_DLK_ORDER_LABEL_DETAIL` ASC),
  INDEX `idx_unit_trace_iot`   (`ID_ITEM_UNICO_IOT` ASC),
  INDEX `idx_unit_trace_activity` (`ID_DLK_ACTIVITIES_ROUTE` ASC),

  CONSTRAINT `fk_OD_UNIT_TRACE_OD_ORDER_LABEL_DETAIL1`
    FOREIGN KEY (`ID_DLK_ORDER_LABEL_DETAIL`)
    REFERENCES `OD_ORDER_LABEL_DETAIL` (`ID_DLK_ORDER_LABEL_DETAIL`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,

  CONSTRAINT `fk_OD_UNIT_TRACE_OD_ACTIVITIES_ROUTE1`
    FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`)
    REFERENCES `OD_ACTIVITIES_ROUTE` (`ID_DLK_ACTIVITIES_ROUTE`)
    ON DELETE SET NULL ON UPDATE NO ACTION
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
