-- Clientes externos (socios) con API Key para ingesta máquina-a-máquina (ej. escaneo DPP).
-- Se guarda el hash SHA-256 de la clave (KEY_HASH), nunca la clave en claro.

CREATE TABLE `MD_API_CLIENT` (
  `ID_DLK_API_CLIENT`    INT NOT NULL AUTO_INCREMENT,
  `NAME_API_CLIENT`      VARCHAR(150) NOT NULL,
  `KEY_HASH`             VARCHAR(64) NOT NULL,
  `KEY_PREFIX`           VARCHAR(20) NOT NULL,
  `SCOPE_API_CLIENT`     VARCHAR(100) NULL,
  `STATE_API_CLIENT`     TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL` DATETIME(3) NULL,
  `DES_ACCION`           VARCHAR(20) NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`     TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_API_CLIENT`),
  UNIQUE KEY `uk_api_client_key_hash` (`KEY_HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
