-- Fase 2 del catálogo de Modelo (aditiva sobre MD_MODEL / MD_MODEL_IMAGES):
--  - imágenes por pieza: FK opcional MD_MODEL_IMAGES.ID_DLK_MODEL_DETAIL → MD_MODEL_DETAIL
--  - ficha técnica como binario: MD_MODEL.TECHNICAL_SPECIFICATION_FILE (MEDIUMBLOB)

ALTER TABLE `MD_MODEL_IMAGES`
  ADD COLUMN `ID_DLK_MODEL_DETAIL` INT NULL AFTER `ID_DLK_MODEL`,
  ADD INDEX `FK_MODEL_IMAGES_DETAIL` (`ID_DLK_MODEL_DETAIL`),
  ADD CONSTRAINT `fk_model_images_detail`
    FOREIGN KEY (`ID_DLK_MODEL_DETAIL`) REFERENCES `MD_MODEL_DETAIL` (`ID_DLK_MODEL_DETAIL`)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `MD_MODEL`
  ADD COLUMN `TECHNICAL_SPECIFICATION_FILE` MEDIUMBLOB NULL AFTER `TECHNICAL_SPECIFICATION`;
