-- Cabecera de orden; FK opcional a MD_BRAND (idempotente en tablas nuevas).
CREATE TABLE IF NOT EXISTS OD_ORDER_HEAD (
  ID_DLK_ORDER_HEAD INT NOT NULL AUTO_INCREMENT,
  ID_DLK_BRAND INT NULL,
  COD_ORDER_HEAD VARCHAR(100) NULL,
  COD_STILO VARCHAR(100) NULL,
  QUANTITY_ORDER_HEAD INT NULL,
  FEC_ENTRY_DATE DATETIME NULL,
  DATE_PROBABLE_DESPATCH_DATE DATETIME NULL,
  STAGE_ORDER_HEAD TINYINT(1) NULL,
  STATUS_STAGE_ORDER_HEAD TINYINT(1) NULL,
  STATE_ORDER_HEAD INT NULL,
  COD_USUARIO_CARGA_DL VARCHAR(20) NULL,
  FEC_PROCESO_CARGA_DL DATETIME(3) NULL,
  FEC_PROCESO_MODIF_DL DATETIME(3) NULL,
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF TINYINT(1) NULL,
  PRIMARY KEY (ID_DLK_ORDER_HEAD),
  CONSTRAINT fk_OD_ORDER_HEAD_MD_BRAND1
    FOREIGN KEY (ID_DLK_BRAND)
    REFERENCES MD_BRAND (ID_DLK_BRAND)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
