-- Flujo Ruta de Producción (por lote, a nivel de componente) + trazabilidad unitaria/IoT
-- 15 tablas nuevas. Generado con prisma migrate diff (filtrando drift preexistente de tablas MD_*/OD_* ajenas).
-- Ver diseño en docs/sql/ruta-produccion.sql

-- CreateTable
CREATE TABLE `OD_ORDER_COMPONENT` (
    `ID_DLK_ORDER_COMPONENT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_HEAD` INTEGER NOT NULL,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_COMPONENT` VARCHAR(50) NULL,
    `NAME_COMPONENT` VARCHAR(200) NULL,
    `STATE_ORDER_COMPONENT` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `idx_component_head`(`ID_DLK_ORDER_HEAD`),
    INDEX `idx_component_detail`(`ID_DLK_ORDER_DETAIL`),
    INDEX `idx_component_code`(`COD_COMPONENT`),
    PRIMARY KEY (`ID_DLK_ORDER_COMPONENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_PROCESS_ROUTE` (
    `ID_DLK_PROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_COMPONENT` INTEGER NOT NULL,
    `ORDEN_PRECEDENCIA_PROCESS` SMALLINT UNSIGNED NOT NULL,
    `COD_PROCESS` VARCHAR(50) NOT NULL,
    `NAME_PROCESS` VARCHAR(100) NOT NULL,
    `CRITICALITY_PROCESS` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    `OUTSOURCED_PROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `ESTIMATED_TIME_PROCESS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `RESPONSIBLE_UNIT` VARCHAR(50) NOT NULL,
    `RESPONSIBLE_PROCESS` VARCHAR(50) NOT NULL,
    `INPUT_TIME_PROCESS_ROUTE` DATETIME(3) NULL,
    `OUTPUT_TIME_PROCESS_ROUTE` DATETIME(3) NULL,
    `STATE_PROCESS_ROUTE` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    UNIQUE INDEX `uq_process_route_precedence`(`ID_DLK_ORDER_COMPONENT`, `ORDEN_PRECEDENCIA_PROCESS`),
    PRIMARY KEY (`ID_DLK_PROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_INPUT_PROCESS_ROUTE` (
    `ID_DLK_INPUT_PROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_PROCESS_ROUTE` INTEGER NOT NULL,
    `COD_INPUT_PROCESS` VARCHAR(50) NOT NULL,
    `NAME_INPUT_PROCESS` VARCHAR(100) NOT NULL,
    `SUPPLIER_INPUT_PROCESS` VARCHAR(120) NULL,
    `FILE_INPUT_PROCESS_ROUTE` VARCHAR(255) NULL,
    `OBSERVATION_INPUT_PROCESS` VARCHAR(255) NULL,
    `STATE_INPUT_PROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_INPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1_idx`(`ID_DLK_PROCESS_ROUTE`),
    INDEX `idx_input_code`(`COD_INPUT_PROCESS`),
    PRIMARY KEY (`ID_DLK_INPUT_PROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_PROCEDURE_PROCESS_ROUTE` (
    `ID_DLK_PROCEDURE_PROCESS` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_PROCESS_ROUTE` INTEGER NOT NULL,
    `COD_PROCEDURE_PROCESS` VARCHAR(50) NOT NULL,
    `NAME_PROCEDURE_PROCESS` VARCHAR(150) NOT NULL,
    `CRITICALITY_PROCEDURE_PROCESS` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    `TIME_PROCEDURE_PROCESS_ROUTE` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `VALIDATION_PROCEDURE_PROCESS` VARCHAR(255) NOT NULL,
    `FILE_PROCEDURE_PROCESS` VARCHAR(255) NULL,
    `STATE_PROCEDURE_PROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_PROCEDURE_PROCESS_ROUTE_idx`(`ID_DLK_PROCESS_ROUTE`),
    INDEX `idx_procedure_code`(`COD_PROCEDURE_PROCESS`),
    PRIMARY KEY (`ID_DLK_PROCEDURE_PROCESS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_OUTPUT_PROCESS_ROUTE` (
    `ID_DLK_OUTPUT_PROCESS` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_PROCESS_ROUTE` INTEGER NOT NULL,
    `COD_OUTPUT_PROCESS` VARCHAR(50) NOT NULL,
    `NAME_OUTPUT_PROCESS` VARCHAR(150) NOT NULL,
    `TYPE_OUTPUT_PROCESS` VARCHAR(50) NOT NULL,
    `DESTINATION_OUTPUT_PROCESS` VARCHAR(100) NOT NULL,
    `UNIT_QUANTITY` DECIMAL(10, 2) NOT NULL DEFAULT 1.00,
    `STATE_OUTPUT_PROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `FILE_OUTPUT_PROCESS_ROUTE` VARCHAR(255) NULL,
    `OBSERVATION_OUTPUT_PROCESS` VARCHAR(255) NULL,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_OUTPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1_idx`(`ID_DLK_PROCESS_ROUTE`),
    INDEX `idx_output_code`(`COD_OUTPUT_PROCESS`),
    PRIMARY KEY (`ID_DLK_OUTPUT_PROCESS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_SUBPROCESS_ROUTE` (
    `ID_DLK_SUBPROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_PROCESS_ROUTE` INTEGER NOT NULL,
    `ORDEN_PRECEDENCIA_SUBPROCESS` SMALLINT UNSIGNED NOT NULL,
    `COD_SUBPROCESS` VARCHAR(20) NOT NULL,
    `NAME_SUBPROCESS` VARCHAR(100) NOT NULL,
    `CRITICALITY_SUBPROCESS` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    `OUTSOURCED_SUBPROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `ESTIMATED_TIME_SUBPROCESS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `RESPONSIBLE_UNIT` VARCHAR(50) NULL,
    `RESPONSIBLE_ROLE` VARCHAR(50) NULL,
    `INPUT_TIME_SUBPROCESS_ROUTE` DATETIME(3) NULL,
    `OUTPUT_TIME_SUBPROCESS_ROUTE` DATETIME(3) NULL,
    `STATE_SUBPROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_SUBPROCESS_ROUTE_OD_PROCESS_ROUTE1_idx`(`ID_DLK_PROCESS_ROUTE`, `ORDEN_PRECEDENCIA_SUBPROCESS`),
    INDEX `idx_subprocess_code`(`COD_SUBPROCESS`),
    UNIQUE INDEX `uq_subprocess_route_precedence`(`ID_DLK_PROCESS_ROUTE`, `ORDEN_PRECEDENCIA_SUBPROCESS`),
    PRIMARY KEY (`ID_DLK_SUBPROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_INPUT_SUBPROCESS_ROUTE` (
    `ID_DLK_INPUT_SUBPROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_SUBPROCESS_ROUTE` INTEGER NOT NULL,
    `COD_INPUT_SUBPROCESS` VARCHAR(50) NOT NULL,
    `NAME_INPUT_SUBPROCESS` VARCHAR(150) NOT NULL,
    `TYPE_INPUT_SUBPROCESS` VARCHAR(50) NOT NULL,
    `SUPPLIER_INPUT_SUBPROCESS` VARCHAR(120) NULL,
    `FILE_INPUT_SUBPROCESS` VARCHAR(255) NULL,
    `OBSERVATION_INPUT_SUBPROCESS` VARCHAR(255) NULL,
    `STATE_INPUT_SUBPROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_INPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1_idx`(`ID_DLK_SUBPROCESS_ROUTE`),
    INDEX `idx_input_sub_code`(`COD_INPUT_SUBPROCESS`),
    PRIMARY KEY (`ID_DLK_INPUT_SUBPROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_PROCEDURE_SUBPROCESS_ROUTE` (
    `ID_DLK_PROCEDURE_SUBPROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_SUBPROCESS_ROUTE` INTEGER NOT NULL,
    `COD_PROCEDURE_SUBPROCESS` VARCHAR(50) NOT NULL,
    `NAME_PROCEDURE_SUBPROCESS` VARCHAR(150) NOT NULL,
    `RESPONSIBLE_PROCEDURE_SUBPROCESS` VARCHAR(100) NOT NULL,
    `ESTIMATED_TIME_PROCEDURE_SUBPROCESS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `CRITICALITY_PROCEDURE_SUBPROCESS` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    `VALIDATION_METHOD_SUBPROCESS` VARCHAR(255) NOT NULL,
    `FILE_PROCEDURE_SUBPROCESS` VARCHAR(255) NULL,
    `STATE_PROCEDURE_SUBPROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_PROCEDURE_SUBPROCESS_ROUTE_SUBPROCESS_idx`(`ID_DLK_SUBPROCESS_ROUTE`),
    INDEX `idx_procedure_sub_code`(`COD_PROCEDURE_SUBPROCESS`),
    PRIMARY KEY (`ID_DLK_PROCEDURE_SUBPROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_OUTPUT_SUBPROCESS_ROUTE` (
    `ID_DLK_OUTPUT_SUBPROCESS_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_SUBPROCESS_ROUTE` INTEGER NOT NULL,
    `COD_OUTPUT_SUBPROCESS` VARCHAR(50) NOT NULL,
    `NAME_OUTPUT_SUBPROCESS` VARCHAR(150) NOT NULL,
    `DESTINATION_OUTPUT_SUBPROCESS` VARCHAR(100) NOT NULL,
    `UNIT_QUANTITY` DECIMAL(10, 2) NOT NULL DEFAULT 1.00,
    `FILE_OUTPUT_SUBPROCESS_ROUTE` VARCHAR(255) NULL,
    `OBSERVATION_OUTPUT_SUBPROCESS` VARCHAR(255) NULL,
    `STATE_OUTPUT_SUBPROCESS` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_OUTPUT_SUBPROCESS_ROUTE_SUBPROCESS_idx`(`ID_DLK_SUBPROCESS_ROUTE`),
    INDEX `idx_output_sub_code`(`COD_OUTPUT_SUBPROCESS`),
    PRIMARY KEY (`ID_DLK_OUTPUT_SUBPROCESS_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_ACTIVITIES_ROUTE` (
    `ID_DLK_ACTIVITIES_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_SUBPROCESS_ROUTE` INTEGER NOT NULL,
    `COD_ACTIVITIES` VARCHAR(20) NOT NULL,
    `NAME_ACTIVITIES` VARCHAR(150) NOT NULL,
    `TYPE_ACTIVITIES` VARCHAR(50) NOT NULL,
    `ORDER_ACTIVITIES` SMALLINT UNSIGNED NOT NULL,
    `ESTIMATED_TIME_ACTIVITIES` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `RESPONSIBLE_NAME` VARCHAR(100) NULL,
    `INPUT_TIME_ACTIVITIES_ROUTE` DATETIME(3) NULL,
    `OUTPUT_TIME_ACTIVITIES_ROUTE` DATETIME(3) NULL,
    `STATE_ACTIVITIES` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_ACTIVITIES_ROUTE_OD_SUBPROCESS_ROUTE1_idx`(`ID_DLK_SUBPROCESS_ROUTE`, `ORDER_ACTIVITIES`),
    INDEX `idx_activities_code`(`COD_ACTIVITIES`),
    UNIQUE INDEX `uq_activities_route_order`(`ID_DLK_SUBPROCESS_ROUTE`, `ORDER_ACTIVITIES`),
    PRIMARY KEY (`ID_DLK_ACTIVITIES_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_INPUT_ACTIVITIES_ROUTE` (
    `ID_DLK_INPUT_ACTIVITIES_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ACTIVITIES_ROUTE` INTEGER NOT NULL,
    `COD_INPUT_ACTIVITIES` VARCHAR(50) NOT NULL,
    `NAME_INPUT_ACTIVITIES` VARCHAR(150) NOT NULL,
    `TYPE_INPUT_ACTIVITIES` VARCHAR(50) NOT NULL,
    `CRITICAL_CHECK_ACTIVITIES` VARCHAR(150) NULL,
    `FILE_INPUT_ACTIVITIES` VARCHAR(255) NULL,
    `OBSERVATION_INPUT_ACTIVITIES` VARCHAR(255) NULL,
    `STATE_INPUT_ACTIVITIES` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_INPUT_ACTIVITIES_ROUTE_ACTIVITIES_idx`(`ID_DLK_ACTIVITIES_ROUTE`),
    INDEX `idx_input_act_code`(`COD_INPUT_ACTIVITIES`),
    PRIMARY KEY (`ID_DLK_INPUT_ACTIVITIES_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_PROCEDURE_ACTIVITIES_ROUTE` (
    `ID_DLK_PROCEDURE_ACTIVITIES_ROUTE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ACTIVITIES_ROUTE` INTEGER NOT NULL,
    `COD_PROCEDURE_ACTIVITIES` VARCHAR(50) NOT NULL,
    `NAME_PROCEDURE_ACTIVITIES` VARCHAR(150) NOT NULL,
    `RESPONSIBLE_EXECUTION` VARCHAR(100) NOT NULL,
    `ESTIMATED_TIME_PROCEDURE` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `CRITICAL_POINT_ACTIVITIES` VARCHAR(255) NOT NULL,
    `FILE_PROCEDURE_ACTIVITIES` VARCHAR(255) NULL,
    `OBSERVATION_ACTIVITIES` VARCHAR(255) NULL,
    `STATE_PROCEDURE_ACTIVITIES` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_PROCEDURE_ACTIVITIES_ROUTE_ACTIVITIES_idx`(`ID_DLK_ACTIVITIES_ROUTE`),
    INDEX `idx_proc_act_code`(`COD_PROCEDURE_ACTIVITIES`),
    PRIMARY KEY (`ID_DLK_PROCEDURE_ACTIVITIES_ROUTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_OUTPUT_ACTIVITIES_ROUTE` (
    `ID_DLK_OUTPUT_ACTIVITIES` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ACTIVITIES_ROUTE` INTEGER NOT NULL,
    `COD_OUTPUT_ACTIVITIES` VARCHAR(50) NOT NULL,
    `NAME_OUTPUT_ACTIVITIES` VARCHAR(150) NOT NULL,
    `TYPE_OUTPUT_ACTIVITIES` VARCHAR(50) NOT NULL,
    `NEXT_DESTINATION_ACTIVITIES` VARCHAR(100) NULL,
    `QUALITY_STANDARD_ACTIVITIES` VARCHAR(255) NULL,
    `FILE_OUTPUT_ACTIVITIES` VARCHAR(255) NULL,
    `STATE_OUTPUT_ACTIVITIES` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `fk_OD_OUTPUT_ACTIVITIES_ROUTE_ACTIVITIES_idx`(`ID_DLK_ACTIVITIES_ROUTE`),
    INDEX `idx_output_act_code`(`COD_OUTPUT_ACTIVITIES`),
    PRIMARY KEY (`ID_DLK_OUTPUT_ACTIVITIES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_UNIT_TRACE` (
    `ID_DLK_UNIT_TRACE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_LABEL_DETAIL` INTEGER NOT NULL,
    `ID_ITEM_UNICO_IOT` VARCHAR(50) NULL,
    `ID_DLK_ACTIVITIES_ROUTE` INTEGER NULL,
    `TYPE_EVENT` VARCHAR(50) NOT NULL,
    `EVENT_TIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `STATE_UNIT_TRACE` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `OBSERVATION_UNIT_TRACE` VARCHAR(255) NULL,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL,
    `DES_ACCION` VARCHAR(10) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT UNSIGNED NOT NULL DEFAULT 1,

    INDEX `idx_unit_trace_label`(`ID_DLK_ORDER_LABEL_DETAIL`),
    INDEX `idx_unit_trace_iot`(`ID_ITEM_UNICO_IOT`),
    INDEX `idx_unit_trace_activity`(`ID_DLK_ACTIVITIES_ROUTE`),
    PRIMARY KEY (`ID_DLK_UNIT_TRACE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `OD_ORDER_COMPONENT` ADD CONSTRAINT `fk_OD_ORDER_COMPONENT_OD_ORDER_HEAD1` FOREIGN KEY (`ID_DLK_ORDER_HEAD`) REFERENCES `OD_ORDER_HEAD`(`ID_DLK_ORDER_HEAD`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_ORDER_COMPONENT` ADD CONSTRAINT `fk_OD_ORDER_COMPONENT_OD_ORDER_DETAIL1` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_PROCESS_ROUTE` ADD CONSTRAINT `fk_OD_PROCESS_ROUTE_OD_ORDER_COMPONENT1` FOREIGN KEY (`ID_DLK_ORDER_COMPONENT`) REFERENCES `OD_ORDER_COMPONENT`(`ID_DLK_ORDER_COMPONENT`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_INPUT_PROCESS_ROUTE` ADD CONSTRAINT `fk_OD_INPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`) REFERENCES `OD_PROCESS_ROUTE`(`ID_DLK_PROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_PROCEDURE_PROCESS_ROUTE` ADD CONSTRAINT `fk_OD_PROCEDURE_PROCESS_OD_PROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`) REFERENCES `OD_PROCESS_ROUTE`(`ID_DLK_PROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_OUTPUT_PROCESS_ROUTE` ADD CONSTRAINT `fk_OD_OUTPUT_PROCESS_ROUTE_OD_PROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`) REFERENCES `OD_PROCESS_ROUTE`(`ID_DLK_PROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_SUBPROCESS_ROUTE` ADD CONSTRAINT `fk_OD_SUBPROCESS_ROUTE_OD_PROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_PROCESS_ROUTE`) REFERENCES `OD_PROCESS_ROUTE`(`ID_DLK_PROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_INPUT_SUBPROCESS_ROUTE` ADD CONSTRAINT `fk_OD_INPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`) REFERENCES `OD_SUBPROCESS_ROUTE`(`ID_DLK_SUBPROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_PROCEDURE_SUBPROCESS_ROUTE` ADD CONSTRAINT `fk_OD_PROCEDURE_SUBPROCESS_OD_SUBPROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`) REFERENCES `OD_SUBPROCESS_ROUTE`(`ID_DLK_SUBPROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_OUTPUT_SUBPROCESS_ROUTE` ADD CONSTRAINT `fk_OD_OUTPUT_SUBPROCESS_OD_SUBPROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`) REFERENCES `OD_SUBPROCESS_ROUTE`(`ID_DLK_SUBPROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_ACTIVITIES_ROUTE` ADD CONSTRAINT `fk_OD_ACTIVITIES_ROUTE_OD_SUBPROCESS_ROUTE1` FOREIGN KEY (`ID_DLK_SUBPROCESS_ROUTE`) REFERENCES `OD_SUBPROCESS_ROUTE`(`ID_DLK_SUBPROCESS_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_INPUT_ACTIVITIES_ROUTE` ADD CONSTRAINT `fk_OD_INPUT_ACTIVITIES_ROUTE_OD_ACTIVITIES_ROUTE1` FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`) REFERENCES `OD_ACTIVITIES_ROUTE`(`ID_DLK_ACTIVITIES_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_PROCEDURE_ACTIVITIES_ROUTE` ADD CONSTRAINT `fk_OD_PROCEDURE_ACTIVITIES_OD_ACTIVITIES_ROUTE1` FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`) REFERENCES `OD_ACTIVITIES_ROUTE`(`ID_DLK_ACTIVITIES_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_OUTPUT_ACTIVITIES_ROUTE` ADD CONSTRAINT `fk_OD_OUTPUT_ACTIVITIES_OD_ACTIVITIES_ROUTE1` FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`) REFERENCES `OD_ACTIVITIES_ROUTE`(`ID_DLK_ACTIVITIES_ROUTE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_UNIT_TRACE` ADD CONSTRAINT `fk_OD_UNIT_TRACE_OD_ORDER_LABEL_DETAIL1` FOREIGN KEY (`ID_DLK_ORDER_LABEL_DETAIL`) REFERENCES `OD_ORDER_LABEL_DETAIL`(`ID_DLK_ORDER_LABEL_DETAIL`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `OD_UNIT_TRACE` ADD CONSTRAINT `fk_OD_UNIT_TRACE_OD_ACTIVITIES_ROUTE1` FOREIGN KEY (`ID_DLK_ACTIVITIES_ROUTE`) REFERENCES `OD_ACTIVITIES_ROUTE`(`ID_DLK_ACTIVITIES_ROUTE`) ON DELETE SET NULL ON UPDATE NO ACTION;
