-- Idempotent schema patch for existing databases (Seenode/prod).
-- Adds missing columns to MD_PARENT_COMPANY and creates Insumos tables if absent.
--
-- Safe for existing data: does not drop tables/columns.

SET @db := DATABASE();

-- ── MD_PARENT_COMPANY: ID_DLK_ADM_REO (nullable) ─────────────────────
SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'MD_PARENT_COMPANY' AND COLUMN_NAME = 'ID_DLK_ADM_REO'
    ),
    'SELECT ''ID_DLK_ADM_REO ya existe'' AS msg',
    'ALTER TABLE MD_PARENT_COMPANY ADD COLUMN ID_DLK_ADM_REO VARCHAR(10) NULL COMMENT ''Código REO SaaS'''
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ── MD_PARENT_COMPANY: TYPE_PARENT_COMPANY (tinyint, default 1) ──────
SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'MD_PARENT_COMPANY' AND COLUMN_NAME = 'TYPE_PARENT_COMPANY'
    ),
    'SELECT ''TYPE_PARENT_COMPANY ya existe'' AS msg',
    'ALTER TABLE MD_PARENT_COMPANY ADD COLUMN TYPE_PARENT_COMPANY TINYINT(1) NOT NULL DEFAULT 1 COMMENT ''1=Marca Propia, 2=Maquila, 3=Híbrido, 4=Comercializadora'''
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ── Insumos: MD_SUPPLIER ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS MD_SUPPLIER (
  ID_DLK_SUPPLIER INT NOT NULL AUTO_INCREMENT,
  COD_SUPPLIER VARCHAR(20),
  NAME_SUPPLIER VARCHAR(200),
  RUC_SUPPLIER VARCHAR(11),
  TYPE_SUPPLIER INT,
  UBIGEO_SUPPLIER VARCHAR(6),
  ADDRESS_SUPPLIER VARCHAR(200),
  GPS_SUPPLIER VARCHAR(100),
  EMAIL_SUPPLIER VARCHAR(100),
  CELULAR_SUPPLIER VARCHAR(25),
  WEB_SUPPLIER VARCHAR(100),
  LOGO_SUPPLIER MEDIUMBLOB,
  STATE_SUPPLIER INT,
  COD_USUARIO_CARGA_DL VARCHAR(20),
  FEH_PROCESO_CARGA_DL DATETIME,
  FEH_PROCESO_MODIF_DL DATETIME,
  DES_ACCION VARCHAR(20),
  FLG_STATUT_ACTIF INT,
  PRIMARY KEY (ID_DLK_SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Insumos: MD_MATERIALS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS MD_MATERIALS (
  ID_DLK_MATERIALS INT NOT NULL AUTO_INCREMENT,
  ID_DLK_SUPPLIER INT NOT NULL,
  COD_MATERIALS VARCHAR(100),
  NAME_MATERIALS VARCHAR(100),
  DES_MATERIALS VARCHAR(500),
  OBS_MATERIALS VARCHAR(500),
  STATE_MATERIALS TINYINT(1),
  COD_USUARIO_CARGA_DL VARCHAR(50),
  FEH_PROCESO_CARGA_DL DATETIME,
  FEH_PROCESO_MODIF_DL DATETIME,
  DES_ACCION VARCHAR(20),
  FLG_STATUT_ACTIF TINYINT(1),
  PRIMARY KEY (ID_DLK_MATERIALS),
  CONSTRAINT FK_MATERIAL_SUPPLIER
    FOREIGN KEY (ID_DLK_SUPPLIER)
    REFERENCES MD_SUPPLIER (ID_DLK_SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Insumos: MD_AVIOS ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS MD_AVIOS (
  ID_DLK_AVIOS INT NOT NULL AUTO_INCREMENT,
  ID_DLK_SUPPLIER INT NOT NULL,
  COD_AVIOS VARCHAR(100),
  NAME_AVIOS VARCHAR(100),
  DES_AVIOS VARCHAR(500),
  OBS_AVIOS VARCHAR(500),
  STATE_AVIOS TINYINT(1),
  COD_USUARIO_CARGA_DL VARCHAR(50),
  FEH_PROCESO_CARGA_DL DATETIME,
  FEH_PROCESO_MODIF_DL DATETIME,
  DES_ACCION VARCHAR(20),
  FLG_STATUT_ACTIF TINYINT(1),
  PRIMARY KEY (ID_DLK_AVIOS),
  CONSTRAINT FK_AVIOS_SUPPLIER
    FOREIGN KEY (ID_DLK_SUPPLIER)
    REFERENCES MD_SUPPLIER (ID_DLK_SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

