-- Proveedores de insumos (DDL negocio). Ejecutar en MariaDB/MySQL.

CREATE TABLE IF NOT EXISTS MD_SUPPLIER (
  ID_DLK_SUPPLIER INT NOT NULL AUTO_INCREMENT,
  COD_SUPPLIER VARCHAR(20) NULL,
  NAME_SUPPLIER VARCHAR(200) NULL,
  RUC_SUPPLIER VARCHAR(11) NULL,
  TYPE_SUPPLIER INT NULL,
  UBIGEO_SUPPLIER VARCHAR(6) NULL,
  ADDRESS_SUPPLIER VARCHAR(200) NULL,
  GPS_SUPPLIER VARCHAR(100) NULL,
  EMAIL_SUPPLIER VARCHAR(100) NULL,
  CELULAR_SUPPLIER VARCHAR(25) NULL,
  WEB_SUPPLIER VARCHAR(100) NULL,
  LOGO_SUPPLIER MEDIUMBLOB NULL,
  STATE_SUPPLIER INT NULL,
  COD_USUARIO_CARGA_DL VARCHAR(20) NULL,
  FEH_PROCESO_CARGA_DL DATETIME NULL,
  FEH_PROCESO_MODIF_DL DATETIME NULL,
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF INT NULL,
  PRIMARY KEY (ID_DLK_SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
