-- Avíos de insumos (FK a MD_SUPPLIER). Tabla MD_AVIOS.

CREATE TABLE IF NOT EXISTS MD_AVIOS (
  ID_DLK_AVIOS INT NOT NULL AUTO_INCREMENT,
  ID_DLK_SUPPLIER INT NOT NULL,
  COD_AVIOS VARCHAR(100) NULL,
  NAME_AVIOS VARCHAR(100) NULL,
  DES_AVIOS VARCHAR(500) NULL,
  OBS_AVIOS VARCHAR(500) NULL,
  STATE_AVIOS TINYINT(1) NULL,
  COD_USUARIO_CARGA_DL VARCHAR(50) NULL,
  FEH_PROCESO_CARGA_DL DATETIME NULL,
  FEH_PROCESO_MODIF_DL DATETIME NULL,
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF TINYINT(1) NULL,
  PRIMARY KEY (ID_DLK_AVIOS),
  CONSTRAINT FK_AVIOS_SUPPLIER
    FOREIGN KEY (ID_DLK_SUPPLIER)
    REFERENCES MD_SUPPLIER (ID_DLK_SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
