-- Columnas de archivo en OD_ORDER_HEAD (idempotente). Misma lógica que la migración Prisma 20260402120000.

SET @db := DATABASE();

SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'NOM_ARCHIVO_ORDER_HEAD'
    ),
    'SELECT 1',
    'ALTER TABLE OD_ORDER_HEAD ADD COLUMN NOM_ARCHIVO_ORDER_HEAD VARCHAR(255) NULL'
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'ARCHIVO_ORDER_HEAD'
    ),
    'SELECT 1',
    'ALTER TABLE OD_ORDER_HEAD ADD COLUMN ARCHIVO_ORDER_HEAD MEDIUMBLOB NULL'
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
