-- DDL objetivo OD_ORDER_HEAD (referencia). En el repo la tabla se obtiene con migraciones
-- 20260401120000 → 20260402120000 → 20260403140000, o aplicando este script en BD vacía
-- y luego añadiendo FKs si los necesitas (marca + detalle).

CREATE TABLE IF NOT EXISTS OD_ORDER_HEAD (
  ID_OLK_ORDER_HEAD INT NOT NULL AUTO_INCREMENT,
  ID_DLK_ORDER_HEAD INT NULL,
  ID_DLK_BRAND INT NULL,
  COD_ORDER_HEAD VARCHAR(100) NULL,
  QUANTITY_ORDER_HEAD INT NULL,
  DATE_ENTRY DATE NULL,
  DATE_PROBABLE_DISPATCH DATE NULL,
  FILE_ORDER_HEAD MEDIUMBLOB NULL,
  STAGE_ORDER_HEAD TINYINT(1) NULL,
  STATUS_STAGE_ORDER_HEAD TINYINT(1) NULL,
  STATE_ORDER_HEAD INT NULL,
  COD_USUARIO_CARGA_OL VARCHAR(20) NULL,
  FECHA_PROCESO_CARGA_OL DATETIME(3) NULL,
  FECHA_PROCESO_MODIF_OL DATETIME(3) NULL,
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF TINYINT(1) NULL,
  PRIMARY KEY (ID_OLK_ORDER_HEAD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Opcional (Prisma / integridad):
-- ALTER TABLE OD_ORDER_HEAD ADD CONSTRAINT fk_OD_ORDER_HEAD_MD_BRAND1
--   FOREIGN KEY (ID_DLK_BRAND) REFERENCES MD_BRAND (ID_DLK_BRAND);
