-- OD_ORDER_HEAD según DDL: FEC_ENTRY / DATE_PROBABLE_DESPATCH como DATE, sin COD_STILO,
-- FK nombrada fk_OD_ORDER_HEAD_MD_BRAND (sustituye fk_OD_ORDER_HEAD_MD_BRAND1 si existía).

ALTER TABLE OD_ORDER_HEAD DROP FOREIGN KEY IF EXISTS fk_OD_ORDER_HEAD_MD_BRAND1;

SET @has_stilo := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'COD_STILO'
);
SET @sql := IF(
  @has_stilo > 0,
  'ALTER TABLE OD_ORDER_HEAD DROP COLUMN COD_STILO',
  'SELECT ''skip_drop_stilo'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_fed := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FEC_ENTRY_DATE'
);
SET @sql := IF(
  @has_fed > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FEC_ENTRY_DATE FEC_ENTRY DATE NULL',
  'SELECT ''skip_fec_entry_date'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_de := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_ENTRY'
);
SET @has_fe := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FEC_ENTRY'
);
SET @sql := IF(
  @has_de > 0 AND @has_fe = 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_ENTRY FEC_ENTRY DATE NULL',
  'SELECT ''skip_date_entry'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_fe2 := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FEC_ENTRY'
);
SET @fe_dt := (
  SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FEC_ENTRY'
  LIMIT 1
);
SET @sql := IF(
  @has_fe2 > 0 AND (@fe_dt = 'datetime' OR @fe_dt = 'timestamp'),
  'ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN FEC_ENTRY DATE NULL',
  'SELECT ''skip_fec_entry_mod'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_dpd_date := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DESPATCH_DATE'
);
SET @sql := IF(
  @has_dpd_date > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_PROBABLE_DESPATCH_DATE DATE_PROBABLE_DESPATCH DATE NULL',
  'SELECT ''skip_dpd_date'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_pd := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DISPATCH'
);
SET @has_dpd := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DESPATCH'
);
SET @sql := IF(
  @has_pd > 0 AND @has_dpd = 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_PROBABLE_DISPATCH DATE_PROBABLE_DESPATCH DATE NULL',
  'SELECT ''skip_prob_dispatch'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_dpd2 := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DESPATCH'
);
SET @dpd_dt := (
  SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DESPATCH'
  LIMIT 1
);
SET @sql := IF(
  @has_dpd2 > 0 AND (@dpd_dt = 'datetime' OR @dpd_dt = 'timestamp'),
  'ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN DATE_PROBABLE_DESPATCH DATE NULL',
  'SELECT ''skip_dpd_mod'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_new := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD'
    AND CONSTRAINT_NAME = 'fk_OD_ORDER_HEAD_MD_BRAND' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
  @fk_new = 0,
  'ALTER TABLE OD_ORDER_HEAD ADD CONSTRAINT fk_OD_ORDER_HEAD_MD_BRAND FOREIGN KEY (ID_DLK_BRAND) REFERENCES MD_BRAND (ID_DLK_BRAND) ON DELETE NO ACTION ON UPDATE NO ACTION',
  'SELECT ''skip_fk_brand'' AS m'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
