// Generado desde prisma/schema.prisma
// Pega este contenido en https://dbdiagram.io/d para visualizar

Enum DeviceType {
  PC
  MOBILE
  TABLET
  BOT
  OTHER
}

Enum AccessStatus {
  SUCCESS
  FAILED
  BLOCKED
  PENDING
}

Enum Criticality {
  LOW
  MEDIUM
  HIGH
}

Table MD_PARENT_COMPANY {
  ID_DLK_PARENT_COMPANY int [pk]
  COD_PARENT_COMPANY VarChar(10) [unique, not null]
  ID_DLK_ADM_REO VarChar(10)
  TYPE_PARENT_COMPANY TinyInt [not null]
  COD_GLN_PARENT_COMPANY VarChar(13) [not null]
  NAME_PARENT_COMPANY VarChar(100) [not null]
  CATEGORY_PARENT_COMPANY int [not null]
  NUM_RUC_PARENT_COMPANY VarChar(11) [unique, not null]
  COD_UBIGEO_PARENT_COMPANY int [not null]
  ADDRESS_PARENT_COMPANY VarChar(200) [not null]
  GPS_LOCATION_PARENT_COMPANY VarChar(100)
  EMAIL_PARENT_COMPANY VarChar(100) [not null]
  CELLULAR_PARENT_COMPANY VarChar(20) [not null]
  WEB_PARENT_COMPANY VarChar(100)
  CANISTER_DATA_PARENT_COMPANY VarChar(100)
  CANISTER_ASSETS_PARENT_COMPANY VarChar(100)
  LOGO_PARENT_COMPANY blob
  STATE_PARENT_COMPANY int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_UBIGEO {
  ID_DLK_UBIGEO int [pk]
  COD_UBIGEO int [not null]
  DES_DEPARTAMENTO VarChar(50) [not null]
  DES_PROVINCIA VarChar(50) [not null]
  DES_DISTRITO VarChar(50) [not null]
  DES_CAPITAL VarChar(50) [not null]
  COD_REGION int [not null]
  DES_REGION VarChar(30) [not null]
  STATE_UBIGEO int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_BRAND {
  ID_DLK_BRAND int [pk]
  COD_BRAND VarChar(10) [unique, not null]
  ID_DLK_PARENT_COMPANY int [not null]
  COD_PARENT_COMPANY VarChar(10) [not null]
  NAME_BRAND VarChar(100) [not null]
  DES_BRAND VarChar(500)
  COD_UBIGEO_BRAND int [not null]
  ADDRESS_BRAND VarChar(200) [not null]
  LOCATION_BRAND VarChar(100)
  EMAIL_BRAND VarChar(100) [not null]
  CELLULAR_BRAND VarChar(20) [not null]
  FACEBOOK_BRAND VarChar(150)
  INSTAGRAM_BRAND VarChar(150)
  WHATSAPP_BRAND VarChar(150)
  ECOMMERCE_BRAND VarChar(150)
  LOGO_BRAND blob
  SUBDOMAIN_BRAND VarChar(100)
  STATE_BRAND int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_SUPPLIER {
  ID_DLK_SUPPLIER int [pk]
  COD_SUPPLIER VarChar(20)
  NAME_SUPPLIER VarChar(200) [not null]
  RUC_SUPPLIER VarChar(11) [not null]
  TYPE_SUPPLIER int [not null]
  UBIGEO_SUPPLIER VarChar(6) [not null]
  ADDRESS_SUPPLIER VarChar(200) [not null]
  GPS_SUPPLIER VarChar(100)
  EMAIL_SUPPLIER VarChar(100) [not null]
  CELLULAR_SUPPLIER VarChar(25) [not null]
  WEB_SUPPLIER VarChar(100)
  LOGO_SUPPLIER blob
  STATE_SUPPLIER int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_MATERIAL {
  ID_DLK_MATERIAL int [pk]
  ID_DLK_SUPPLIER int [not null]
  COD_MATERIAL VarChar(100)
  MATERIAL VarChar(200)
  CONTENT_NAME_MATERIAL VarChar(200)
  CONTENT_VALUE_MATERIAL Decimal(5, 2)
  CONTENT_SOURCE_MATERIALS VarChar(100)
  MATERIAL_TRADE_MARKS VarChar(100)
  RECYCLED TinyInt
  PERCENTAGE_RECYCLED_MATERIALS Decimal(5, 2)
  RECYCLED_INPUT_SOURCE VarChar(500)
  RENEWABLE_MATERIAL TinyInt
  PERCENTAGE_RENEWABLE_MATERIAL Decimal(5, 2)
  RENEWABLE_INPUT_SOURCE VarChar(100)
  TYPE_DYES VarChar(100)
  DYE_CLASS VarChar(100)
  CLASS_STANDARD_DYES VarChar(100)
  FINISHES VarChar(100)
  PATTERNS VarChar(100)
  RECOVERY_MATERIALS VarChar(100)
  CERTIFICATION VarChar(1000)
  ORDER_FORM VarChar(20)
  COLOR_MATERIAL VarChar(100)
  ROLL_MATERIAL VarChar(45)
  INVOICE_MATERIAL VarChar(45)
  STATE_MATERIALS TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL datetime
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table MD_AVIO {
  ID_DLK_AVIO int [pk]
  ID_DLK_SUPPLIER int [not null]
  COD_AVIO VarChar(100)
  TYPE_AVIO VarChar(100)
  NAME_AVIO VarChar(200)
  MATERIAL_AVIO VarChar(500)
  CONTENT_VALUE_MATERIAL Decimal(5, 2)
  CONTENT_SOURCE_MATERIAL VarChar(100)
  MATERIAL_TRADE_MARKS VarChar(100)
  COLOR VarChar(200)
  WEIGHT Decimal(10, 3)
  UNIT_MEASUREMENT VarChar(20)
  RECYCLED TinyInt
  PERCENTAGE_RECYCLED_MATERIALS Decimal(5, 2)
  RECYCLED_INPUT_SOURCE VarChar(500)
  CERTIFICATES VarChar(1000)
  OBSERVATION VarChar(500)
  ORDER_FORM VarChar(20)
  MEASURES_AVIO VarChar(100)
  INVOICE_AVIO VarChar(45)
  STATE_AVIOS TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL datetime
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table MD_ORDEN_PEDIDO {
  ID_DLK_ORDEN_PEDIDO int [pk]
  COD_ORDEN_PEDIDO VarChar(20) [not null]
  ID_DLK_PARENT_COMPANY int [not null]
  CANTIDAD int [not null]
  FECHA_INGRESO datetime [not null]
  PROBABLE_DESPACHO datetime [not null]
  ETAPA int [not null]
  ESTADO int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table OD_ORDER_HEAD {
  ID_DLK_ORDER_HEAD int [pk]
  ID_DLK_BRAND int [not null]
  COD_ORDER_HEAD VarChar(100) [not null]
  QUANTITY_ORDER_HEAD int [not null]
  DATE_ENTRY Date [not null]
  DATE_PROBABLE_DISPATCH Date [not null]
  FILE_ORDER_HEAD MediumBlob
  STAGE_ORDER_HEAD TinyInt
  STATUS_STAGE_ORDER_HEAD TinyInt
  FILE_SUPPLIES_UDP MediumBlob
  FEH_FILE_SUPPLIES_UDP Date
  FILE_SUPPLIES_PROD MediumBlob
  FEH_FILE_SUPPLIES_PROD Date
  FILE_SUPPLIES_FINAL MediumBlob
  FEH_FILE_SUPPLIES_FINAL Date
  STATE_ORDER_HEAD TinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF TinyInt [not null]
}

Table OD_ORDER_DETAIL {
  ID_DLK_ORDER_DETAIL int [pk]
  ID_DLK_ORDER_HEAD int [not null]
  COD_ORDER_DETAIL VarChar(50)
  COD_ESTILO VarChar(50)
  NAME_ESTILO VarChar(200)
  IMG_ESTILO MediumBlob
  DES_TELA VarChar(200)
  COLOR_AWAY VarChar(50)
  FONDO_TELA VarChar(50)
  VERSION_TELA VarChar(50)
  ORDER_SAMPLE TinyInt
  SIZE_0_3 int
  SIZE_3_6 int
  SIZE_0_6 int
  SIZE_6_12 int
  SIZE_12_18 int
  SIZE_2 int
  SIZE_3 int
  SIZE_4 int
  SIZE_5 int
  SIZE_6 int
  SIZE_7 int
  SIZE_8 int
  SIZE_9 int
  SIZE_10 int
  SIZE_11 int
  SIZE_12 int
  SIZE_14 int
  SIZE_16 int
  SIZE_XS int
  SIZE_S int
  SIZE_M int
  SIZE_L int
  SIZE_XL int
  SIZE_XXL int
  TOTAL_ORDER_PRODUCTION int
  ES_SET TinyInt [not null]
  NUM_PIEZAS int [not null]
  SUPPLY_FILE MediumBlob
  STATE_ORDER_DETAIL TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL DateTime(3)
  FEH_PROCESO_MODIF_DL DateTime(3)
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table MD_PRODUCTION_CHAIN {
  ID_DLK_PRODUCTION_CHAIN int [pk]
  COD_PRODUCTION_CHAIN VarChar(10) [unique, not null]
  COD_CATEGORY_PRODUCTION_CHAIN int [not null]
  NUM_PRECEDENCIA_TRAZABILIDAD int [not null]
  NUM_PRECEDENCIA_PRODUCTIVA int [not null]
  NAME_PRODUCTION_CHAIN VarChar(100) [not null]
  DES_PRODUCTION_CHAIN VarChar(1000) [not null]
  STATE_PRODUCTION_CHAIN int [not null]
  COD_USUARIO_CARGA_DL VarChar(50) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(50)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_PROCESS {
  ID_DLK_PROCESS int [pk]
  ID_DLK_PARENT_COMPANY int [not null]
  ID_DLK_PRODUCTION_CHAIN int [not null]
  ORDEN_PRECEDENCIA_PROCESS int [not null]
  COD_PROCESS VarChar(100) [not null]
  NAME_PROCESS VarChar(100) [not null]
  DES_PROCESS VarChar(1000) [not null]
  OBJETIVE_PROCESS VarChar(1000) [not null]
  CRITICALITY_PROCESS VarChar(200) [not null]
  OUTSOURCED_PROCESS VarChar(250) [not null]
  ESTIMATED_TIME_PROCESS int [not null]
  RESPONSIBLE_UNIT VarChar(100) [not null]
  RESPONSIBLE_PROCESS VarChar(100) [not null]
  PROCESS_CERTIFICATION VarChar(1000)
  STATE_PROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_SUBPROCESS {
  ID_DLK_SUBPROCESS int [pk]
  ID_DLK_PROCESS int [not null]
  ORDEN_PRECEDENCIA_SUBPROCESS int
  COD_SUBPROCESS VarChar(100) [not null]
  NAME_SUBPROCESS VarChar(100) [not null]
  DESCRIPTION_SUBPROCESS VarChar(1000) [not null]
  OBJECTIVE_SUBPROCESS VarChar(1000)
  CRITICALITY_SUBPROCESS VarChar(200)
  OUTSOURCED_SUBPROCESS VarChar(250)
  ESTIMATED_TIME_SUBPROCESS int
  RESPONSIBLE_UNIT VarChar(100)
  RESPONSIBLE_ROLE VarChar(100)
  CERTIFICATION_SUBPROCESS VarChar(1000)
  STATE_SUBPROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_ACTIVITIES {
  ID_DLK_ACTIVITIES int [pk]
  ID_DLK_SUBPROCESS int [not null]
  COD_ACTIVITIES VarChar(100) [not null]
  NAME_ACTIVITIES VarChar(200) [not null]
  DESCRIPTION_ACTIVITIES VarChar(1000) [not null]
  TYPE_ACTIVITIES VarChar(200) [not null]
  ORDER_ACTIVITIES int
  ESTIMATED_TIME_ACTIVITIES VarChar(200)
  MACHINE_REQUIRED VarChar(200)
  SKILL_REQUIRED VarChar(200)
  CHECKLIST_ACTIVITIES VarChar(200)
  STATE_ACTIVITIES int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_INPUT_PROCESS {
  ID_DLK_INPUT_PROCESS int [pk]
  ID_DLK_PROCESS int [not null]
  COD_INPUT_PROCESS VarChar(200) [not null]
  NAME_INPUT_PROCESS VarChar(200) [not null]
  DESCRIPTION_INPUT_PROCESS VarChar(200) [not null]
  TYPE_INPUT_PROCESS VarChar(200) [not null]
  ORIGIN_INPUT_PROCESS VarChar(200) [not null]
  AMOUNT_INPUT_PROCESS VarChar(200) [not null]
  UNIT_QUANTITY VarChar(200) [not null]
  SUPPLIER_INPUT_PROCESS VarChar(200)
  CERTIFICATION_INPUT_PROCESS VarChar(200)
  OBSERVATION_INPUT_PROCESS VarChar(200)
  STATE_INPUT_PROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_INPUT_SUBPROCESS {
  ID_DLK_INPUT_SUBPROCESS int [pk]
  ID_DLK_SUBPROCESS int [not null]
  COD_INPUT_SUBPROCESS VarChar(200) [not null]
  NAME_INPUT_SUBPROCESS VarChar(200) [not null]
  DESCRIPTION_INPUT_SUBPROCESS VarChar(200) [not null]
  TYPE_INPUT_SUBPROCESS VarChar(200) [not null]
  ORIGIN_INPUT_SUBPROCESS VarChar(200) [not null]
  AMOUNT_INPUT_SUBPROCESS VarChar(200) [not null]
  UNIT_QUANTITY VarChar(200) [not null]
  SUPPLIER_INPUT_SUBPROCESS VarChar(200)
  CERTIFICATION_INPUT_SUBPROCESS VarChar(200)
  OBSERVATION_INPUT_SUBPROCESS VarChar(200)
  STATE_INPUT_SUBPROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_INPUT_ACTIVITIES {
  ID_DLK_INPUT_ACTIVITIES int [pk]
  ID_DLK_ACTIVITIES int [not null]
  COD_INPUT_ACTIVITIES VarChar(200) [not null]
  NAME_INPUT_ACTIVITIES VarChar(200) [not null]
  DESCRIPTION_INPUT_ACTIVITIES VarChar(1000) [not null]
  TYPE_INPUT_ACTIVITIES VarChar(200) [not null]
  AMOUNT_REQUIRED_ACTIVITIES VarChar(200) [not null]
  UNIT_MEASURE_ACTIVITIES VarChar(200) [not null]
  SOURCE_INPUT_ACTIVITIES VarChar(200)
  TECHNICAL_SPEC_ACTIVITIES VarChar(200)
  CRITICAL_CHECK_ACTIVITIES VarChar(200)
  STATE_INPUT_ACTIVITIES int [not null]
  COD_USUARIO_CARGA_DL VarChar(50) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(50) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_OUTPUT_PROCESS {
  ID_DLK_OUTPUT_PROCESS int [pk]
  ID_DLK_PROCESS int [not null]
  COD_OUTPUT_PROCESS VarChar(200) [not null]
  NAME_OUTPUT_PROCESS VarChar(200) [not null]
  DESCRIPTION_OUTPUT_PROCESS VarChar(200) [not null]
  TYPE_OUTPUT_PROCESS VarChar(200) [not null]
  DESTINATION_OUTPUT_PROCESS VarChar(200) [not null]
  AMOUNT_OUTPUT_PROCESS VarChar(200) [not null]
  UNIT_QUANTITY VarChar(200) [not null]
  STATE_OUTPUT_PROCESS VarChar(200) [not null]
  CERTIFICATION_OUTPUT_PROCESS VarChar(200)
  OBSERVATION_OUTPUT_PROCESS VarChar(200)
  STATE_OUTPUT int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_OUTPUT_SUBPROCESS {
  ID_DLK_OUTPUT_SUBPROCESS int [pk]
  ID_DLK_SUBPROCESS int [not null]
  COD_OUTPUT_SUBPROCESS VarChar(200) [not null]
  NAME_OUTPUT_SUBPROCESS VarChar(200) [not null]
  DESCRIPTION_OUTPUT_SUBPROCESS VarChar(200) [not null]
  TYPE_OUTPUT_SUBPROCESS VarChar(200) [not null]
  DESTINATION_OUTPUT_SUBPROCESS VarChar(200) [not null]
  AMOUNT_OUTPUT_SUBPROCESS VarChar(200) [not null]
  UNIT_QUANTITY VarChar(200) [not null]
  STATE_OUTPUT_SUBPROCESS VarChar(200) [not null]
  CERTIFICATION_OUTPUT_SUBPROCESS VarChar(200)
  OBSERVATION_OUTPUT_SUBPROCESS Text
  STATE_OUTPUT int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_OUTPUT_ACTIVITIES {
  ID_DLK_OUTPUT_ACTIVITIES int [pk]
  ID_DLK_ACTIVITIES int [not null]
  COD_OUTPUT_ACTIVITIES VarChar(200) [not null]
  NAME_OUTPUT_ACTIVITIES VarChar(200) [not null]
  DESCRIPTION_OUTPUT_ACTIVITIES VarChar(1000) [not null]
  TYPE_OUTPUT_ACTIVITIES VarChar(200) [not null]
  AMOUNT_EXPECTED_ACTIVITIES VarChar(200) [not null]
  UNIT_MEASURE_OUTPUT VarChar(200) [not null]
  NEXT_DESTINATION_ACTIVITIES VarChar(200)
  QUALITY_STANDARD_ACTIVITIES VarChar(200)
  STATE_OUTPUT_ACTIVITIES int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_PROCEDURE_PROCESS {
  ID_DLK_PROCEDURE_PROCESS int [pk]
  ID_DLK_PROCESS int [not null]
  COD_PROCEDURE_PROCESS VarChar(200) [not null]
  NAME_PROCEDURE_PROCESS VarChar(200) [not null]
  DESCRIPTION_PROCEDURE_PROCESS VarChar(200) [not null]
  RESPONSIBLE_PROCEDURE_PROCESS VarChar(200) [not null]
  STATE_PROCEDURE_PROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
  CRITICALLY_PROCEDURE_PROCESS VarChar(200) [not null]
  PCC_PROCEDURE_PROCESS VarChar(200) [not null]
  TIME_PROCEDURE_PROCESS VarChar(200) [not null]
  VALIDATION_PROCEDURE_PROCESS VarChar(200) [not null]
}

Table MD_PROCEDURE_SUBPROCESS {
  ID_DLK_PROCEDURE_SUBPROCESS int [pk]
  ID_DLK_SUBPROCESS int [not null]
  COD_PROCEDURE_SUBPROCESS VarChar(200) [not null]
  NAME_PROCEDURE_SUBPROCESS VarChar(200) [not null]
  DESCRIPTION_PROCEDURE_SUBPROCESS VarChar(200) [not null]
  TYPE_PROCEDURE_SUBPROCESS VarChar(200) [not null]
  RESPONSIBLE_PROCEDURE_SUBPROCESS VarChar(200) [not null]
  ESTIMATED_TIME_SUBPROCESS VarChar(200) [not null]
  CRITICALITY_SUBPROCESS VarChar(200) [not null]
  VALIDATION_METHOD_SUBPROCESS VarChar(200) [not null]
  PCC_SUBPROCESS VarChar(200) [not null]
  STATE_PROCEDURE_SUBPROCESS int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_PROCEDURE_ACTIVITIES {
  ID_DLK_PROCEDURE_ACTIVITIES int [pk]
  ID_DLK_ACTIVITIES int [not null]
  COD_PROCEDURE_ACTIVITIES VarChar(200) [not null]
  NAME_PROCEDURE_ACTIVITIES VarChar(200) [not null]
  DESCRIPTION_PROCEDURE_ACTIVITIES VarChar(1000) [not null]
  TYPE_PROCEDURE_ACTIVITIES VarChar(200) [not null]
  RESPONSIBLE_EXECUTION VarChar(200) [not null]
  ESTIMATED_TIME_PROCEDURE VarChar(200) [not null]
  CRITICAL_POINT_ACTIVITIES VarChar(200) [not null]
  SAFETY_REQUIREMENT VarChar(200) [not null]
  VALIDATION_METHOD VarChar(200) [not null]
  STATE_PROCEDURE_ACTIVITIES int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF int [not null]
}

Table MD_FACILITY {
  ID_DLK_FACILITY int [pk]
  COD_FACILITY VarChar(10) [unique, not null]
  ID_DLK_PARENT_COMPANY int [not null]
  COD_UBIGEO int [not null]
  COD_GLN_FACILITY VarChar(13) [not null]
  REGISTRY_FACILITY VarChar(20) [not null]
  IDENTIFIER_FACILITY VarChar(20) [not null]
  NAME_FACILITY VarChar(100) [not null]
  ADDRESS_FACILITY VarChar(200) [not null]
  GPS_LOCATION_FACILITY VarChar(100)
  EMAIL_FACILITY VarChar(100) [not null]
  CELLULAR_FACILITY VarChar(20) [not null]
  STATE_FACILITY int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_MAQUILA {
  ID_DLK_MAQUILA int [pk]
  COD_MAQUILA VarChar(10) [unique, not null]
  COD_GLN_MAQUILA VarChar(13)
  NAME_MAQUILA VarChar(100) [not null]
  CATEGORY_MAQUILA int [not null]
  NUM_RUC_MAQUILA VarChar(11) [not null]
  COD_UBIGEO int [not null]
  ADDRESS_MAQUILA VarChar(200) [not null]
  GPS_LOCATION_MAQUILA VarChar(100)
  EMAIL_MAQUILA VarChar(100) [not null]
  CELLULAR_MAQUILA VarChar(20) [not null]
  WEB_MAQUILA VarChar(100) [not null]
  CANISTER_DATA_MAQUILA int [not null]
  CANISTER_ASSETS_MAQUILA VarChar(100) [not null]
  LOGO_MAQUILA blob [not null]
  STATE_MAQUILA int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_FACILITY_MAQUILA {
  ID_DLK_FACILITY_MAQUILA int [pk]
  COD_FACILITY_MAQUILA VarChar(10) [unique, not null]
  ID_DLK_MAQUILA int [not null]
  COD_MAQUILA VarChar(10) [not null]
  COD_UBIGEO int [not null]
  COD_GLN_FACILITY_MAQUILA VarChar(13)
  REGISTRY_FACILITY_MAQUILA VarChar(20) [not null]
  IDENTIFIER_FACILITY_MAQUILA VarChar(20) [not null]
  NAME_FACILITY_MAQUILA VarChar(100) [not null]
  ADDRESS_FACILITY_MAQUILA VarChar(200) [not null]
  GPS_LOCATION_FACILITY_MAQUILA VarChar(100)
  EMAIL_FACILITY_MAQUILA VarChar(100) [not null]
  CELLULAR_FACILITY_MAQUILA VarChar(20) [not null]
  STATE_FACILITY_MAQUILA int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_PARENT_COMPANY_MAQUILA {
  ID_DLK_PARENT_COMPANY_MAQUILA int [pk]
  COD_PARENT_COMPANY VarChar(10) [not null]
  COD_MAQUILA VarChar(10) [not null]
  STATE_PARENT_COMPANY_MAQUILA int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_SUBBRAND {
  ID_DLK_SUBBRAND int [pk]
  COD_SUBBRAND VarChar(10) [unique, not null]
  ID_DLK_BRAND int [not null]
  COD_BRAND VarChar(10) [not null]
  NAME_SUBBRAND VarChar(100) [not null]
  COD_UBIGEO_SUBBRAND int [not null]
  ADDRESS_SUBBRAND VarChar(200) [not null]
  LOCATION_SUBBRAND VarChar(100)
  EMAIL_SUBBRAND VarChar(100) [not null]
  CELLULAR_SUBBRAND VarChar(20) [not null]
  FACEBOOK_SUBBRAND VarChar(150)
  INSTAGRAM_SUBBRAND VarChar(150)
  WHATSAPP_SUBBRAND VarChar(150)
  ECOMMERCE_SUBBRAND VarChar(150)
  LOGO_SUBBRAND blob
  STATE_SUBBRAND int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_USER_REO {
  ID_DLK_USER_REO int [pk]
  COD_USER_REO VarChar(20) [unique, not null]
  ID_DLK_PARENT_COMPANY int [not null]
  COD_PARENT_COMPANY VarChar(10) [not null]
  DOCUMENT_TYPE int [not null]
  DOCUMENT_NUMBER VarChar(15) [not null]
  NAME_USER VarChar(100) [not null]
  PATERNAL_LAST_NAME_USER VarChar(100) [not null]
  MATERNAL_LAST_NAME_USER VarChar(100) [not null]
  SEX_USER VarChar(1) [not null]
  POSITION_USER int [not null]
  ROL_USER int [not null]
  EMAIL_USER VarChar(100) [not null]
  CELLULAR_USER VarChar(20) [not null]
  USER_LOGIN VarChar(20) [unique, not null]
  PASSWORD VarChar(255) [not null]
  PHOTOGRAPH blob
  FAILED_ATTEMPTS int
  IS_LOCKED int
  LOCKED_UNTIL datetime
  LAST_LOGIN_DATE datetime
  LAST_LOGIN_IP VarChar(45)
  PASSWORD_EXPIRES_AT datetime
  TWO_FACTOR_SECRET VarChar(255)
  TWO_FACTOR_ENABLED int [not null]
  STATE_USER int [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL datetime [not null]
  FEH_PROCESO_MODIF_DL datetime [not null]
  DES_ACCION VarChar(20) [not null]
  FLG_STATUT_ACTIF int [not null]
}

Table MD_USER_BACKUP_CODES {
  ID_BACKUP_CODE bigint [pk]
  ID_DLK_USER_REO int [not null]
  CODE_HASH VarChar(60) [not null]
  USED_AT DateTime(3)
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
}

Table LG_USER_ACCESS {
  ID_LOG_ACCESS bigint [pk]
  ID_DLK_USER_REO int [not null]
  IP_ADDRESS VarChar(45) [not null]
  BROWSER VarChar(50)
  BROWSER_VERSION VarChar(50)
  OPERATING_SYSTEM VarChar(50)
  DEVICE_TYPE DeviceType [not null]
  LATITUDE Decimal(10, 8)
  LONGITUDE Decimal(11, 8)
  CITY VarChar(100)
  COUNTRY VarChar(100)
  ACCESS_STATUS AccessStatus [not null]
  FEH_ACCESS DateTime(3) [not null]
  USER_AGENT_RAW Text
}

Table LG_PARENT_COMPANY {
  ID_AUDIT bigint [pk]
  ID_DLK_PARENT_COMPANY int [not null]
  TYPE_OPERATION VarChar(6) [not null]
  IP_ACCESO VarChar(45) [not null]
  USER_AGENT VarChar(500)
  AUDIT_USUARIO VarChar(50) [not null]
  FECHA_CAMBIO datetime
  COD_PARENT_COMPANY VarChar(10)
  COD_GLN_PARENT_COMPANY VarChar(13)
  NAME_PARENT_COMPANY VarChar(100)
  CATEGORY_PARENT_COMPANY int
  NUM_RUC_PARENT_COMPANY VarChar(11)
  COD_UBIGEO_PARENT_COMPANY int
  ADDRESS_PARENT_COMPANY VarChar(200)
  GPS_LOCATION_PARENT_COMPANY VarChar(100)
  EMAIL_PARENT_COMPANY VarChar(100)
  CELLULAR_PARENT_COMPANY VarChar(20)
  WEB_PARENT_COMPANY VarChar(100)
  CANISTER_DATA_PARENT_COMPANY VarChar(100)
  CANISTER_ASSETS_PARENT_COMPANY VarChar(100)
  LOGO_PARENT_COMPANY blob
}

Table MD_DIGITAL_IDENTIFIER {
  ID_DLK_DIGITAL_IDENTIFIER int [pk]
  COD_DIGITAL_IDENTIFIER VarChar(255) [unique, not null]
  TYPE_DIGITAL_IDENTIFIER VarChar(100)
  MATERIAL_DIGITAL_IDENTIFIER VarChar(150)
  LOCATION_DIGITAL_IDENTIFIER VarChar(255)
  STANDARD_ISO_DIGITAL_IDENTIFIER VarChar(100)
  SUPPLIER_DIGITAL_IDENTIFIER VarChar(150)
  MODEL_DIGITAL_IDENTIFIER VarChar(150)
  SPECIFICATION_DIGITAL_IDENTIFIER MediumBlob
  OBSERVATION_DIGITAL_IDENTIFIER Text
  STATE_DIGITAL_IDENTIFIER TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL DateTime(0)
  FEH_PROCESO_MODIF_DL DateTime(0)
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table OD_ORDER_LABEL_HEAD {
  ID_DLK_ORDER_LABEL_HEAD int [pk]
  ID_DLK_ORDER_HEAD int [not null]
  ID_DLK_DIGITAL_IDENTIFIER int [not null]
  ID_DLK_ORDER_DETAIL int
  COD_ORDER_LABEL VarChar(20)
  COD_ESTILO VarChar(50)
  NAME_ESTILO VarChar(200)
  DESCRIPTION_ESTILO Text
  GENDER_ESTILO VarChar(45)
  SEASON_ESTILO VarChar(45)
  COD_GTIN VarChar(14)
  SIZE VarChar(50)
  ESTAMPADO VarChar(100)
  IDENTIFIER_TYPE VarChar(45)
  IDENTIFIER_MATERIAL VarChar(500)
  IDENTIFIER_LOCATION VarChar(200)
  INICIO_SERIALIZACION int
  FIN_SERIALIZACION int
  TOTAL_LABEL int
  SIGN_OPEN_RESPONSIBLE Text
  FEH_SIGN_OPEN DateTime(3)
  SIGN_CLOSE_RESPONSIBLE Text
  FEH_SIGN_CLOSE DateTime(3)
  DIGITAL_CERTIFICATE_ID VarChar(100)
  STATE_ORDER_LABEL_HEAD TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL DateTime(3)
  FEH_PROCESO_MODIF_DL DateTime(3)
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table OD_ORDER_LABEL_DETAIL {
  ID_DLK_ORDER_LABEL_DETAIL int [pk]
  ID_DLK_ORDER_LABEL_HEAD int [not null]
  ID_DLK_ORDER_LABEL_COMPONENT int
  ID_DLK_DIGITAL_IDENTIFIER int
  ITEM_GLOBAL int [not null]
  ITEM_BY_SIZE int [not null]
  SERIAL_NUMBER VarChar(20) [not null]
  SGTIN_FULL VarChar(150) [unique, not null]
  URL_DPP_FULL VarChar(1000) [not null]
  COLOR VarChar(100)
  PRINT VarChar(100)
  SIZE VarChar(50)
  PIECE_TYPE VarChar(45)
  SET_GROUP_ID VarChar(50)
  IS_BLACKLISTED TinyInt
  REASON_BLACKLIST VarChar(100)
  STATE_ORDER_LABEL_DETAIL TinyInt
  FEH_PROCESO_CARGA_DL DateTime(3)
  FEH_PROCESO_MODIF_DL DateTime(3)
  COD_USUARIO_AUDITOR VarChar(20)
}

Table OD_ORDER_LABEL_COMPONENT {
  ID_DLK_ORDER_LABEL_COMPONENT int [pk]
  ID_DLK_ORDER_LABEL_HEAD int [not null]
  ID_DLK_ORDER_DETAIL int [not null]
  ID_DLK_DIGITAL_IDENTIFIER int [not null]
  NUM_PIECE int [not null]
  NAME_COMPONENT VarChar(200)
  COD_COMPONENT VarChar(50)
  STATE_ORDER_LABEL_COMPONENT TinyInt
  COD_USUARIO_CARGA_DL VarChar(20)
  FEH_PROCESO_CARGA_DL DateTime(3)
  FEH_PROCESO_MODIF_DL DateTime(3)
  DES_ACCION VarChar(20)
  FLG_STATUT_ACTIF TinyInt
}

Table OD_ORDER_COMPONENT {
  ID_DLK_ORDER_COMPONENT int [pk]
  ID_DLK_ORDER_HEAD int [not null]
  ID_DLK_ORDER_DETAIL int [not null]
  COD_COMPONENT VarChar(50)
  NAME_COMPONENT VarChar(200)
  STATE_ORDER_COMPONENT UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_PROCESS_ROUTE {
  ID_DLK_PROCESS_ROUTE int [pk]
  ID_DLK_ORDER_COMPONENT int [not null]
  ORDEN_PRECEDENCIA_PROCESS UnsignedSmallInt [not null]
  COD_PROCESS VarChar(50) [not null]
  NAME_PROCESS VarChar(100) [not null]
  CRITICALITY_PROCESS Criticality [not null]
  OUTSOURCED_PROCESS UnsignedTinyInt [not null]
  ESTIMATED_TIME_PROCESS UnsignedInt [not null]
  RESPONSIBLE_UNIT VarChar(50) [not null]
  RESPONSIBLE_PROCESS VarChar(50) [not null]
  INPUT_TIME_PROCESS_ROUTE DateTime(3)
  OUTPUT_TIME_PROCESS_ROUTE DateTime(3)
  STATE_PROCESS_ROUTE UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_INPUT_PROCESS_ROUTE {
  ID_DLK_INPUT_PROCESS_ROUTE int [pk]
  ID_DLK_PROCESS_ROUTE int [not null]
  COD_INPUT_PROCESS VarChar(50) [not null]
  NAME_INPUT_PROCESS VarChar(100) [not null]
  SUPPLIER_INPUT_PROCESS VarChar(120)
  FILE_INPUT_PROCESS_ROUTE VarChar(255)
  OBSERVATION_INPUT_PROCESS VarChar(255)
  STATE_INPUT_PROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_PROCEDURE_PROCESS_ROUTE {
  ID_DLK_PROCEDURE_PROCESS int [pk]
  ID_DLK_PROCESS_ROUTE int [not null]
  COD_PROCEDURE_PROCESS VarChar(50) [not null]
  NAME_PROCEDURE_PROCESS VarChar(150) [not null]
  CRITICALITY_PROCEDURE_PROCESS Criticality [not null]
  TIME_PROCEDURE_PROCESS_ROUTE UnsignedInt [not null]
  VALIDATION_PROCEDURE_PROCESS VarChar(255) [not null]
  FILE_PROCEDURE_PROCESS VarChar(255)
  STATE_PROCEDURE_PROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_OUTPUT_PROCESS_ROUTE {
  ID_DLK_OUTPUT_PROCESS int [pk]
  ID_DLK_PROCESS_ROUTE int [not null]
  COD_OUTPUT_PROCESS VarChar(50) [not null]
  NAME_OUTPUT_PROCESS VarChar(150) [not null]
  TYPE_OUTPUT_PROCESS VarChar(50) [not null]
  DESTINATION_OUTPUT_PROCESS VarChar(100) [not null]
  UNIT_QUANTITY Decimal(10, 2) [not null]
  STATE_OUTPUT_PROCESS UnsignedTinyInt [not null]
  FILE_OUTPUT_PROCESS_ROUTE VarChar(255)
  OBSERVATION_OUTPUT_PROCESS VarChar(255)
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_SUBPROCESS_ROUTE {
  ID_DLK_SUBPROCESS_ROUTE int [pk]
  ID_DLK_PROCESS_ROUTE int [not null]
  ORDEN_PRECEDENCIA_SUBPROCESS UnsignedSmallInt [not null]
  COD_SUBPROCESS VarChar(20) [not null]
  NAME_SUBPROCESS VarChar(100) [not null]
  CRITICALITY_SUBPROCESS Criticality [not null]
  OUTSOURCED_SUBPROCESS UnsignedTinyInt [not null]
  ESTIMATED_TIME_SUBPROCESS UnsignedInt [not null]
  RESPONSIBLE_UNIT VarChar(50)
  RESPONSIBLE_ROLE VarChar(50)
  INPUT_TIME_SUBPROCESS_ROUTE DateTime(3)
  OUTPUT_TIME_SUBPROCESS_ROUTE DateTime(3)
  STATE_SUBPROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_INPUT_SUBPROCESS_ROUTE {
  ID_DLK_INPUT_SUBPROCESS_ROUTE int [pk]
  ID_DLK_SUBPROCESS_ROUTE int [not null]
  COD_INPUT_SUBPROCESS VarChar(50) [not null]
  NAME_INPUT_SUBPROCESS VarChar(150) [not null]
  TYPE_INPUT_SUBPROCESS VarChar(50) [not null]
  SUPPLIER_INPUT_SUBPROCESS VarChar(120)
  FILE_INPUT_SUBPROCESS VarChar(255)
  OBSERVATION_INPUT_SUBPROCESS VarChar(255)
  STATE_INPUT_SUBPROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_PROCEDURE_SUBPROCESS_ROUTE {
  ID_DLK_PROCEDURE_SUBPROCESS_ROUTE int [pk]
  ID_DLK_SUBPROCESS_ROUTE int [not null]
  COD_PROCEDURE_SUBPROCESS VarChar(50) [not null]
  NAME_PROCEDURE_SUBPROCESS VarChar(150) [not null]
  RESPONSIBLE_PROCEDURE_SUBPROCESS VarChar(100) [not null]
  ESTIMATED_TIME_PROCEDURE_SUBPROCESS UnsignedInt [not null]
  CRITICALITY_PROCEDURE_SUBPROCESS Criticality [not null]
  VALIDATION_METHOD_SUBPROCESS VarChar(255) [not null]
  FILE_PROCEDURE_SUBPROCESS VarChar(255)
  STATE_PROCEDURE_SUBPROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_OUTPUT_SUBPROCESS_ROUTE {
  ID_DLK_OUTPUT_SUBPROCESS_ROUTE int [pk]
  ID_DLK_SUBPROCESS_ROUTE int [not null]
  COD_OUTPUT_SUBPROCESS VarChar(50) [not null]
  NAME_OUTPUT_SUBPROCESS VarChar(150) [not null]
  DESTINATION_OUTPUT_SUBPROCESS VarChar(100) [not null]
  UNIT_QUANTITY Decimal(10, 2) [not null]
  FILE_OUTPUT_SUBPROCESS_ROUTE VarChar(255)
  OBSERVATION_OUTPUT_SUBPROCESS VarChar(255)
  STATE_OUTPUT_SUBPROCESS UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_ACTIVITIES_ROUTE {
  ID_DLK_ACTIVITIES_ROUTE int [pk]
  ID_DLK_SUBPROCESS_ROUTE int [not null]
  COD_ACTIVITIES VarChar(20) [not null]
  NAME_ACTIVITIES VarChar(150) [not null]
  TYPE_ACTIVITIES VarChar(50) [not null]
  ORDER_ACTIVITIES UnsignedSmallInt [not null]
  ESTIMATED_TIME_ACTIVITIES UnsignedInt [not null]
  RESPONSIBLE_NAME VarChar(100)
  INPUT_TIME_ACTIVITIES_ROUTE DateTime(3)
  OUTPUT_TIME_ACTIVITIES_ROUTE DateTime(3)
  STATE_ACTIVITIES UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_INPUT_ACTIVITIES_ROUTE {
  ID_DLK_INPUT_ACTIVITIES_ROUTE int [pk]
  ID_DLK_ACTIVITIES_ROUTE int [not null]
  COD_INPUT_ACTIVITIES VarChar(50) [not null]
  NAME_INPUT_ACTIVITIES VarChar(150) [not null]
  TYPE_INPUT_ACTIVITIES VarChar(50) [not null]
  CRITICAL_CHECK_ACTIVITIES VarChar(150)
  FILE_INPUT_ACTIVITIES VarChar(255)
  OBSERVATION_INPUT_ACTIVITIES VarChar(255)
  STATE_INPUT_ACTIVITIES UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_PROCEDURE_ACTIVITIES_ROUTE {
  ID_DLK_PROCEDURE_ACTIVITIES_ROUTE int [pk]
  ID_DLK_ACTIVITIES_ROUTE int [not null]
  COD_PROCEDURE_ACTIVITIES VarChar(50) [not null]
  NAME_PROCEDURE_ACTIVITIES VarChar(150) [not null]
  RESPONSIBLE_EXECUTION VarChar(100) [not null]
  ESTIMATED_TIME_PROCEDURE UnsignedInt [not null]
  CRITICAL_POINT_ACTIVITIES VarChar(255) [not null]
  FILE_PROCEDURE_ACTIVITIES VarChar(255)
  OBSERVATION_ACTIVITIES VarChar(255)
  STATE_PROCEDURE_ACTIVITIES UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_OUTPUT_ACTIVITIES_ROUTE {
  ID_DLK_OUTPUT_ACTIVITIES int [pk]
  ID_DLK_ACTIVITIES_ROUTE int [not null]
  COD_OUTPUT_ACTIVITIES VarChar(50) [not null]
  NAME_OUTPUT_ACTIVITIES VarChar(150) [not null]
  TYPE_OUTPUT_ACTIVITIES VarChar(50) [not null]
  NEXT_DESTINATION_ACTIVITIES VarChar(100)
  QUALITY_STANDARD_ACTIVITIES VarChar(255)
  FILE_OUTPUT_ACTIVITIES VarChar(255)
  STATE_OUTPUT_ACTIVITIES UnsignedTinyInt [not null]
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Table OD_UNIT_TRACE {
  ID_DLK_UNIT_TRACE int [pk]
  ID_DLK_ORDER_LABEL_DETAIL int [not null]
  ID_ITEM_UNICO_IOT VarChar(50)
  ID_DLK_ACTIVITIES_ROUTE int
  TYPE_EVENT VarChar(50) [not null]
  EVENT_TIME DateTime(3) [not null]
  STATE_UNIT_TRACE UnsignedTinyInt [not null]
  OBSERVATION_UNIT_TRACE VarChar(255)
  COD_USUARIO_CARGA_DL VarChar(20) [not null]
  FEH_PROCESO_CARGA_DL DateTime(3) [not null]
  FEH_PROCESO_MODIF_DL DateTime(3) [not null]
  DES_ACCION VarChar(10) [not null]
  FLG_STATUT_ACTIF UnsignedTinyInt [not null]
}

Ref: MD_BRAND.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: MD_MATERIAL.ID_DLK_SUPPLIER > MD_SUPPLIER.ID_DLK_SUPPLIER
Ref: MD_AVIO.ID_DLK_SUPPLIER > MD_SUPPLIER.ID_DLK_SUPPLIER
Ref: MD_ORDEN_PEDIDO.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: OD_ORDER_HEAD.ID_DLK_BRAND > MD_BRAND.ID_DLK_BRAND
Ref: OD_ORDER_DETAIL.ID_DLK_ORDER_HEAD > OD_ORDER_HEAD.ID_DLK_ORDER_HEAD
Ref: MD_PROCESS.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: MD_PROCESS.ID_DLK_PRODUCTION_CHAIN > MD_PRODUCTION_CHAIN.ID_DLK_PRODUCTION_CHAIN
Ref: MD_SUBPROCESS.ID_DLK_PROCESS > MD_PROCESS.ID_DLK_PROCESS
Ref: MD_ACTIVITIES.ID_DLK_SUBPROCESS > MD_SUBPROCESS.ID_DLK_SUBPROCESS
Ref: MD_INPUT_PROCESS.ID_DLK_PROCESS > MD_PROCESS.ID_DLK_PROCESS
Ref: MD_INPUT_SUBPROCESS.ID_DLK_SUBPROCESS > MD_SUBPROCESS.ID_DLK_SUBPROCESS
Ref: MD_INPUT_ACTIVITIES.ID_DLK_ACTIVITIES > MD_ACTIVITIES.ID_DLK_ACTIVITIES
Ref: MD_OUTPUT_PROCESS.ID_DLK_PROCESS > MD_PROCESS.ID_DLK_PROCESS
Ref: MD_OUTPUT_SUBPROCESS.ID_DLK_SUBPROCESS > MD_SUBPROCESS.ID_DLK_SUBPROCESS
Ref: MD_OUTPUT_ACTIVITIES.ID_DLK_ACTIVITIES > MD_ACTIVITIES.ID_DLK_ACTIVITIES
Ref: MD_PROCEDURE_PROCESS.ID_DLK_PROCESS > MD_PROCESS.ID_DLK_PROCESS
Ref: MD_PROCEDURE_SUBPROCESS.ID_DLK_SUBPROCESS > MD_SUBPROCESS.ID_DLK_SUBPROCESS
Ref: MD_PROCEDURE_ACTIVITIES.ID_DLK_ACTIVITIES > MD_ACTIVITIES.ID_DLK_ACTIVITIES
Ref: MD_FACILITY.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: MD_FACILITY_MAQUILA.ID_DLK_MAQUILA > MD_MAQUILA.ID_DLK_MAQUILA
Ref: MD_PARENT_COMPANY_MAQUILA.COD_MAQUILA > MD_MAQUILA.COD_MAQUILA
Ref: MD_PARENT_COMPANY_MAQUILA.COD_PARENT_COMPANY > MD_PARENT_COMPANY.COD_PARENT_COMPANY
Ref: MD_SUBBRAND.ID_DLK_BRAND > MD_BRAND.ID_DLK_BRAND
Ref: MD_USER_REO.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: MD_USER_BACKUP_CODES.ID_DLK_USER_REO > MD_USER_REO.ID_DLK_USER_REO
Ref: LG_USER_ACCESS.ID_DLK_USER_REO > MD_USER_REO.ID_DLK_USER_REO
Ref: LG_PARENT_COMPANY.ID_DLK_PARENT_COMPANY > MD_PARENT_COMPANY.ID_DLK_PARENT_COMPANY
Ref: OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_HEAD > OD_ORDER_HEAD.ID_DLK_ORDER_HEAD
Ref: OD_ORDER_LABEL_HEAD.ID_DLK_DIGITAL_IDENTIFIER > MD_DIGITAL_IDENTIFIER.ID_DLK_DIGITAL_IDENTIFIER
Ref: OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_DETAIL > OD_ORDER_DETAIL.ID_DLK_ORDER_DETAIL
Ref: OD_ORDER_LABEL_DETAIL.ID_DLK_ORDER_LABEL_HEAD > OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_LABEL_HEAD
Ref: OD_ORDER_LABEL_DETAIL.ID_DLK_ORDER_LABEL_COMPONENT > OD_ORDER_LABEL_COMPONENT.ID_DLK_ORDER_LABEL_COMPONENT
Ref: OD_ORDER_LABEL_DETAIL.ID_DLK_DIGITAL_IDENTIFIER > MD_DIGITAL_IDENTIFIER.ID_DLK_DIGITAL_IDENTIFIER
Ref: OD_ORDER_LABEL_COMPONENT.ID_DLK_ORDER_LABEL_HEAD > OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_LABEL_HEAD
Ref: OD_ORDER_LABEL_COMPONENT.ID_DLK_ORDER_DETAIL > OD_ORDER_DETAIL.ID_DLK_ORDER_DETAIL
Ref: OD_ORDER_LABEL_COMPONENT.ID_DLK_DIGITAL_IDENTIFIER > MD_DIGITAL_IDENTIFIER.ID_DLK_DIGITAL_IDENTIFIER
Ref: OD_ORDER_COMPONENT.ID_DLK_ORDER_HEAD > OD_ORDER_HEAD.ID_DLK_ORDER_HEAD
Ref: OD_ORDER_COMPONENT.ID_DLK_ORDER_DETAIL > OD_ORDER_DETAIL.ID_DLK_ORDER_DETAIL
Ref: OD_PROCESS_ROUTE.ID_DLK_ORDER_COMPONENT > OD_ORDER_COMPONENT.ID_DLK_ORDER_COMPONENT
Ref: OD_INPUT_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE > OD_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE
Ref: OD_PROCEDURE_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE > OD_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE
Ref: OD_OUTPUT_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE > OD_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE
Ref: OD_SUBPROCESS_ROUTE.ID_DLK_PROCESS_ROUTE > OD_PROCESS_ROUTE.ID_DLK_PROCESS_ROUTE
Ref: OD_INPUT_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE > OD_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE
Ref: OD_PROCEDURE_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE > OD_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE
Ref: OD_OUTPUT_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE > OD_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE
Ref: OD_ACTIVITIES_ROUTE.ID_DLK_SUBPROCESS_ROUTE > OD_SUBPROCESS_ROUTE.ID_DLK_SUBPROCESS_ROUTE
Ref: OD_INPUT_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE > OD_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE
Ref: OD_PROCEDURE_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE > OD_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE
Ref: OD_OUTPUT_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE > OD_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE
Ref: OD_UNIT_TRACE.ID_DLK_ORDER_LABEL_DETAIL > OD_ORDER_LABEL_DETAIL.ID_DLK_ORDER_LABEL_DETAIL
Ref: OD_UNIT_TRACE.ID_DLK_ACTIVITIES_ROUTE > OD_ACTIVITIES_ROUTE.ID_DLK_ACTIVITIES_ROUTE
