-- Indicadores de sostenibilidad por detalle de orden (insumos del DPP):
--   OD_CARBON_FOOTPRINT      huella de carbono por talla
--   OD_WATER_FOOTPRINT       huella hídrica por talla
--   OD_RESTRICTED_SUBSTANCES sustancias restringidas / químicos
--   OD_CIRCULAR_ECONOMY      economía circular
--   OD_SOCIAL_IMPACT         impacto social
-- Todas cuelgan de OD_ORDER_DETAIL (1:N) y siguen el patrón DLK del resto
-- del esquema: DATETIME(3) para que case con @db.DateTime(3) de Prisma, y
-- FEH_PROCESO_MODIF_DL gestionado por la app (@updatedAt), sin
-- ON UPDATE CURRENT_TIMESTAMP, como en el resto de tablas OD_*.
-- Aditiva: sólo crea tablas nuevas.

-- CreateTable
CREATE TABLE `OD_CARBON_FOOTPRINT` (
    `ID_DLK_CARBON_FOOTPRINT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_CARBON_FOOTPRINT` VARCHAR(50) NOT NULL,
    `SIZE` VARCHAR(10) NOT NULL,
    `WEIGHT` DECIMAL(10, 4) NOT NULL,
    `CARBON_FOOTPRINT` DECIMAL(10, 4) NOT NULL,
    `ESTIMATED_VALUE` TINYINT NOT NULL DEFAULT 0,
    `UNIT_DESCRIPTION` VARCHAR(500) NOT NULL,
    `SCOPE` VARCHAR(1000) NOT NULL,
    `REPORT` VARCHAR(500) NULL,
    `STATE_CARBON_FOOTPRINT` TINYINT NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` INTEGER NOT NULL DEFAULT 1,
    INDEX `idx_carbon_footprint_order_detail`(`ID_DLK_ORDER_DETAIL`),
    PRIMARY KEY (`ID_DLK_CARBON_FOOTPRINT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_WATER_FOOTPRINT` (
    `ID_DLK_WATER_FOOTPRINT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_WATER_FOOTPRINT` VARCHAR(50) NOT NULL,
    `SIZE` VARCHAR(10) NOT NULL,
    `WEIGHT` DECIMAL(10, 4) NOT NULL,
    `WATER_FOOTPRINT` DECIMAL(10, 4) NOT NULL,
    `ESTIMATED_VALUE` TINYINT NOT NULL DEFAULT 0,
    `UNIT_DESCRIPTION` VARCHAR(500) NOT NULL,
    `SCOPE` VARCHAR(1000) NOT NULL,
    `REPORT` VARCHAR(500) NULL,
    `STATE_WATER_FOOTPRINT` TINYINT NOT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NOT NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` INTEGER NOT NULL DEFAULT 1,
    INDEX `idx_water_footprint_order_detail`(`ID_DLK_ORDER_DETAIL`),
    PRIMARY KEY (`ID_DLK_WATER_FOOTPRINT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_RESTRICTED_SUBSTANCES` (
    `ID_DLK_RESTRICTED_SUBSTANCES` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_RESTRICTED_SUBSTANCES` VARCHAR(50) NOT NULL,
    `WEIGHT` DECIMAL(10, 4) NULL,
    `RESTRICTED_SUBSTANCES` VARCHAR(100) NULL,
    `TOPIC` VARCHAR(100) NULL,
    `CONTENT` VARCHAR(1000) NULL,
    `CHEMICAL_SCOPE` VARCHAR(1000) NULL,
    `REPORT` VARCHAR(500) NULL,
    `STATE_RESTRICTED_SUBSTANCES` TINYINT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` INTEGER NULL DEFAULT 1,
    INDEX `idx_restricted_substances_order_detail`(`ID_DLK_ORDER_DETAIL`),
    PRIMARY KEY (`ID_DLK_RESTRICTED_SUBSTANCES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_CIRCULAR_ECONOMY` (
    `ID_DLK_CIRCULAR_ECONOMY` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_CIRCULAR_ECONOMY` VARCHAR(50) NOT NULL,
    `IMAGE` VARCHAR(500) NULL,
    `DESCRIPTION` VARCHAR(200) NULL,
    `TOPIC` VARCHAR(100) NULL,
    `CONTENT` VARCHAR(1000) NULL,
    `REPORT` VARCHAR(500) NULL,
    `STATE_CIRCULAR_ECONOMY` TINYINT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` INTEGER NULL DEFAULT 1,
    INDEX `idx_circular_economy_order_detail`(`ID_DLK_ORDER_DETAIL`),
    PRIMARY KEY (`ID_DLK_CIRCULAR_ECONOMY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OD_SOCIAL_IMPACT` (
    `ID_DLK_SOCIAL_IMPACT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `COD_SOCIAL_IMPACT` VARCHAR(50) NOT NULL,
    `FEMALE_WORKFORCE` VARCHAR(100) NULL,
    `LEADERSHIP` VARCHAR(200) NULL,
    `WORKING_CONDITIONS` VARCHAR(100) NULL,
    `COMMITMENT_OIT` VARCHAR(100) NULL,
    `SCOPE` VARCHAR(500) NULL,
    `REFERENCE_STANDARD` VARCHAR(1000) NULL,
    `REPORT` VARCHAR(500) NULL,
    `STATE_SOCIAL_IMPACT` TINYINT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` INTEGER NULL DEFAULT 1,
    INDEX `idx_social_impact_order_detail`(`ID_DLK_ORDER_DETAIL`),
    PRIMARY KEY (`ID_DLK_SOCIAL_IMPACT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `OD_CARBON_FOOTPRINT` ADD CONSTRAINT `fk_carbon_footprint_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_WATER_FOOTPRINT` ADD CONSTRAINT `fk_water_footprint_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_RESTRICTED_SUBSTANCES` ADD CONSTRAINT `fk_restricted_substances_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_CIRCULAR_ECONOMY` ADD CONSTRAINT `fk_circular_economy_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_SOCIAL_IMPACT` ADD CONSTRAINT `fk_social_impact_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;
