-- OD_ORDER_HEAD: PK ID_OLK_ORDER_HEAD, ID_DLK_ORDER_HEAD nullable (negocio), columnas según DDL nuevo.
-- OD_ORDER_DETAIL: FK por ID_OLK_ORDER_HEAD.
-- Requiere esquema previo creado por migraciones 20260401120000 + archivo + detail.

-- IF EXISTS: MySQL 8.0.29+ / MariaDB 10.5.2+ (evita fallo si la migración se reintenta).
ALTER TABLE OD_ORDER_DETAIL DROP FOREIGN KEY IF EXISTS fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1;
ALTER TABLE OD_ORDER_HEAD DROP FOREIGN KEY IF EXISTS fk_OD_ORDER_HEAD_MD_BRAND1;

-- Quitar AUTO_INCREMENT de ID_DLK_ORDER_HEAD si sigue activo (sin esto, DROP PRIMARY KEY da 1075 en MariaDB).
SET @ai := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD'
    AND COLUMN_NAME = 'ID_DLK_ORDER_HEAD' AND EXTRA LIKE '%auto_increment%'
);
SET @sql := IF(
  @ai > 0,
  'ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_DLK_ORDER_HEAD INT NOT NULL',
  'SELECT ''skip_modify_dlk_ai'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_pk := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND CONSTRAINT_TYPE = 'PRIMARY KEY'
);
SET @sql2 := IF(
  @has_pk > 0,
  'ALTER TABLE OD_ORDER_HEAD DROP PRIMARY KEY',
  'SELECT ''skip_drop_pk'' AS msg'
);
PREPARE stmt2 FROM @sql2;
EXECUTE stmt2;
DEALLOCATE PREPARE stmt2;

ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_DLK_ORDER_HEAD INT NULL;

SET @has_olk := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'ID_OLK_ORDER_HEAD'
);
SET @sql3 := IF(
  @has_olk = 0,
  'ALTER TABLE OD_ORDER_HEAD ADD COLUMN ID_OLK_ORDER_HEAD INT NULL',
  'SELECT ''skip_add_olk'' AS msg'
);
PREPARE stmt3 FROM @sql3;
EXECUTE stmt3;
DEALLOCATE PREPARE stmt3;
UPDATE OD_ORDER_HEAD SET ID_OLK_ORDER_HEAD = ID_DLK_ORDER_HEAD WHERE ID_OLK_ORDER_HEAD IS NULL;
ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_OLK_ORDER_HEAD INT NOT NULL;
ALTER TABLE OD_ORDER_HEAD ADD PRIMARY KEY (ID_OLK_ORDER_HEAD);
ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_OLK_ORDER_HEAD INT NOT NULL AUTO_INCREMENT;

ALTER TABLE OD_ORDER_HEAD DROP COLUMN COD_STILO;

ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FEC_ENTRY_DATE DATE_ENTRY DATE NULL;
ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_PROBABLE_DESPATCH_DATE DATE_PROBABLE_DISPATCH DATE NULL;

ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN COD_USUARIO_CARGA_DL COD_USUARIO_CARGA_OL VARCHAR(20) NULL;
ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FEC_PROCESO_CARGA_DL FECHA_PROCESO_CARGA_OL DATETIME(3) NULL;
ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FEC_PROCESO_MODIF_DL FECHA_PROCESO_MODIF_OL DATETIME(3) NULL;

ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN ARCHIVO_ORDER_HEAD FILE_ORDER_HEAD MEDIUMBLOB NULL;
ALTER TABLE OD_ORDER_HEAD DROP COLUMN NOM_ARCHIVO_ORDER_HEAD;

ALTER TABLE OD_ORDER_DETAIL ADD COLUMN ID_OLK_ORDER_HEAD INT NULL;
UPDATE OD_ORDER_DETAIL d
INNER JOIN OD_ORDER_HEAD h ON d.ID_DLK_ORDER_HEAD = h.ID_DLK_ORDER_HEAD
SET d.ID_OLK_ORDER_HEAD = h.ID_OLK_ORDER_HEAD
WHERE d.ID_DLK_ORDER_HEAD IS NOT NULL;

ALTER TABLE OD_ORDER_DETAIL DROP COLUMN ID_DLK_ORDER_HEAD;

ALTER TABLE OD_ORDER_DETAIL ADD CONSTRAINT fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1
  FOREIGN KEY (ID_OLK_ORDER_HEAD)
  REFERENCES OD_ORDER_HEAD (ID_OLK_ORDER_HEAD)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE OD_ORDER_HEAD ADD CONSTRAINT fk_OD_ORDER_HEAD_MD_BRAND1
  FOREIGN KEY (ID_DLK_BRAND)
  REFERENCES MD_BRAND (ID_DLK_BRAND)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
