-- Identificador digital por pieza de set: nueva tabla OD_ORDER_LABEL_COMPONENT
-- y enlaces en OD_ORDER_LABEL_DETAIL (set → componente; no-set → identificador directo).

-- CreateTable
CREATE TABLE `OD_ORDER_LABEL_COMPONENT` (
    `ID_DLK_ORDER_LABEL_COMPONENT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DLK_ORDER_LABEL_HEAD` INTEGER NOT NULL,
    `ID_DLK_ORDER_DETAIL` INTEGER NOT NULL,
    `ID_DLK_DIGITAL_IDENTIFIER` INTEGER NOT NULL,
    `NUM_PIECE` INTEGER NOT NULL,
    `NAME_COMPONENT` VARCHAR(200) NULL,
    `COD_COMPONENT` VARCHAR(50) NULL,
    `STATE_ORDER_LABEL_COMPONENT` TINYINT NULL DEFAULT 1,
    `COD_USUARIO_CARGA_DL` VARCHAR(20) NULL,
    `FEH_PROCESO_CARGA_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FEH_PROCESO_MODIF_DL` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DES_ACCION` VARCHAR(20) NULL DEFAULT 'INSERT',
    `FLG_STATUT_ACTIF` TINYINT NULL DEFAULT 1,
    UNIQUE INDEX `uq_label_component_head_piece`(`ID_DLK_ORDER_LABEL_HEAD`, `NUM_PIECE`),
    INDEX `idx_label_component_head`(`ID_DLK_ORDER_LABEL_HEAD`),
    INDEX `idx_label_component_order_detail`(`ID_DLK_ORDER_DETAIL`),
    INDEX `idx_label_component_digital`(`ID_DLK_DIGITAL_IDENTIFIER`),
    PRIMARY KEY (`ID_DLK_ORDER_LABEL_COMPONENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AlterTable
ALTER TABLE `OD_ORDER_LABEL_DETAIL`
    ADD COLUMN `ID_DLK_ORDER_LABEL_COMPONENT` INTEGER NULL,
    ADD COLUMN `ID_DLK_DIGITAL_IDENTIFIER` INTEGER NULL;

-- CreateIndex
CREATE INDEX `idx_label_detail_component` ON `OD_ORDER_LABEL_DETAIL`(`ID_DLK_ORDER_LABEL_COMPONENT`);

-- CreateIndex
CREATE INDEX `idx_label_detail_digital` ON `OD_ORDER_LABEL_DETAIL`(`ID_DLK_DIGITAL_IDENTIFIER`);

-- AddForeignKey
ALTER TABLE `OD_ORDER_LABEL_COMPONENT` ADD CONSTRAINT `fk_label_component_head` FOREIGN KEY (`ID_DLK_ORDER_LABEL_HEAD`) REFERENCES `OD_ORDER_LABEL_HEAD`(`ID_DLK_ORDER_LABEL_HEAD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_ORDER_LABEL_COMPONENT` ADD CONSTRAINT `fk_label_component_order_detail` FOREIGN KEY (`ID_DLK_ORDER_DETAIL`) REFERENCES `OD_ORDER_DETAIL`(`ID_DLK_ORDER_DETAIL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_ORDER_LABEL_COMPONENT` ADD CONSTRAINT `fk_label_component_digital` FOREIGN KEY (`ID_DLK_DIGITAL_IDENTIFIER`) REFERENCES `MD_DIGITAL_IDENTIFIER`(`ID_DLK_DIGITAL_IDENTIFIER`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_ORDER_LABEL_DETAIL` ADD CONSTRAINT `fk_label_detail_component` FOREIGN KEY (`ID_DLK_ORDER_LABEL_COMPONENT`) REFERENCES `OD_ORDER_LABEL_COMPONENT`(`ID_DLK_ORDER_LABEL_COMPONENT`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OD_ORDER_LABEL_DETAIL` ADD CONSTRAINT `fk_label_detail_digital` FOREIGN KEY (`ID_DLK_DIGITAL_IDENTIFIER`) REFERENCES `MD_DIGITAL_IDENTIFIER`(`ID_DLK_DIGITAL_IDENTIFIER`) ON DELETE RESTRICT ON UPDATE CASCADE;
