-- Prisma mapea el blob a FILE_ORDER_HEAD. La migración 20260402120000 creó ARCHIVO_ORDER_HEAD.
-- La 20260403140000 (OLK) lo renombraba pero quedó en no-op; esta migración alinea el nombre.

SET @db := DATABASE();

SET @has_file := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FILE_ORDER_HEAD'
);
SET @has_archivo := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'ARCHIVO_ORDER_HEAD'
);

SET @sql := IF(
  @has_file > 0,
  'SELECT ''skip_file_order_head_exists'' AS msg',
  IF(
    @has_archivo > 0,
    'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN ARCHIVO_ORDER_HEAD FILE_ORDER_HEAD MEDIUMBLOB NULL',
    'ALTER TABLE OD_ORDER_HEAD ADD COLUMN FILE_ORDER_HEAD MEDIUMBLOB NULL'
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
