-- Restaura OD_ORDER_HEAD con PK ID_DLK_ORDER_HEAD (DDL negocio: FEC_* DATETIME, *_DL, COD_STILO, FILE_ORDER_HEAD).
-- Compatible con BD que nunca pasaron por el pivot OLK (20260403140000 es no-op) y con MySQL sin DROP FK IF EXISTS.

SET @db := DATABASE();

SET @fk_det := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_DETAIL'
    AND CONSTRAINT_NAME = 'fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
  @fk_det > 0,
  'ALTER TABLE OD_ORDER_DETAIL DROP FOREIGN KEY fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1',
  'SELECT ''skip_drop_detail_fk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_brand := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD'
    AND CONSTRAINT_NAME = 'fk_OD_ORDER_HEAD_MD_BRAND1' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
  @fk_brand > 0,
  'ALTER TABLE OD_ORDER_HEAD DROP FOREIGN KEY fk_OD_ORDER_HEAD_MD_BRAND1',
  'SELECT ''skip_drop_brand_fk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @det_dlk := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_DETAIL' AND COLUMN_NAME = 'ID_DLK_ORDER_HEAD'
);
SET @sql := IF(
  @det_dlk = 0,
  'ALTER TABLE OD_ORDER_DETAIL ADD COLUMN ID_DLK_ORDER_HEAD INT NULL',
  'SELECT ''detail_has_dlk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_olk_d := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_DETAIL' AND COLUMN_NAME = 'ID_OLK_ORDER_HEAD'
);
SET @has_olk_h := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'ID_OLK_ORDER_HEAD'
);
SET @sql := IF(
  @has_olk_d > 0 AND @has_olk_h > 0,
  'UPDATE OD_ORDER_DETAIL d INNER JOIN OD_ORDER_HEAD h ON d.ID_OLK_ORDER_HEAD = h.ID_OLK_ORDER_HEAD SET d.ID_DLK_ORDER_HEAD = COALESCE(h.ID_DLK_ORDER_HEAD, h.ID_OLK_ORDER_HEAD) WHERE d.ID_OLK_ORDER_HEAD IS NOT NULL',
  'SELECT ''skip_detail_update'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  @has_olk_d > 0,
  'ALTER TABLE OD_ORDER_DETAIL DROP COLUMN IF EXISTS ID_OLK_ORDER_HEAD',
  'SELECT ''skip_drop_olk_d'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @ai_olk := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD'
    AND COLUMN_NAME = 'ID_OLK_ORDER_HEAD' AND EXTRA LIKE '%auto_increment%'
);
SET @sql := IF(
  @has_olk_h > 0 AND @ai_olk > 0,
  'ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_OLK_ORDER_HEAD INT NOT NULL',
  'SELECT ''skip_olk_ai'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_pk := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND CONSTRAINT_TYPE = 'PRIMARY KEY'
);
SET @sql := IF(
  @has_olk_h > 0 AND @has_pk > 0,
  'ALTER TABLE OD_ORDER_HEAD DROP PRIMARY KEY',
  'SELECT ''skip_drop_pk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  @has_olk_h > 0,
  'UPDATE OD_ORDER_HEAD SET ID_DLK_ORDER_HEAD = ID_OLK_ORDER_HEAD WHERE ID_DLK_ORDER_HEAD IS NULL AND ID_OLK_ORDER_HEAD IS NOT NULL',
  'SELECT ''skip_head_dlk_fill'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  @has_olk_h > 0,
  'ALTER TABLE OD_ORDER_HEAD DROP COLUMN IF EXISTS ID_OLK_ORDER_HEAD',
  'SELECT ''skip_drop_olk_h'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  @has_olk_h > 0,
  'ALTER TABLE OD_ORDER_HEAD MODIFY COLUMN ID_DLK_ORDER_HEAD INT NOT NULL AUTO_INCREMENT PRIMARY KEY',
  'SELECT ''skip_pk_dlk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_date_entry := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_ENTRY'
);
SET @sql := IF(
  @has_date_entry > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_ENTRY FEC_ENTRY_DATE DATETIME NULL',
  'SELECT ''skip_date_entry'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_date_pd := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'DATE_PROBABLE_DISPATCH'
);
SET @sql := IF(
  @has_date_pd > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN DATE_PROBABLE_DISPATCH DATE_PROBABLE_DESPATCH_DATE DATETIME NULL',
  'SELECT ''skip_date_pd'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_c_ol := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'COD_USUARIO_CARGA_OL'
);
SET @sql := IF(
  @has_c_ol > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN COD_USUARIO_CARGA_OL COD_USUARIO_CARGA_DL VARCHAR(20) NULL',
  'SELECT ''skip_c_ol'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_fca_ol := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FECHA_PROCESO_CARGA_OL'
);
SET @sql := IF(
  @has_fca_ol > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FECHA_PROCESO_CARGA_OL FEC_PROCESO_CARGA_DL DATETIME(3) NULL',
  'SELECT ''skip_fca_ol'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_fmo_ol := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'FECHA_PROCESO_MODIF_OL'
);
SET @sql := IF(
  @has_fmo_ol > 0,
  'ALTER TABLE OD_ORDER_HEAD CHANGE COLUMN FECHA_PROCESO_MODIF_OL FEC_PROCESO_MODIF_DL DATETIME(3) NULL',
  'SELECT ''skip_fmo_ol'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @has_stilo := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'COD_STILO'
);
SET @sql := IF(
  @has_stilo = 0,
  'ALTER TABLE OD_ORDER_HEAD ADD COLUMN COD_STILO VARCHAR(100) NULL',
  'SELECT ''skip_cod_stilo'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_det_add := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_DETAIL'
    AND CONSTRAINT_NAME = 'fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
  @fk_det_add = 0,
  'ALTER TABLE OD_ORDER_DETAIL ADD CONSTRAINT fk_OD_ORDER_DETAIL_OD_ORDER_HEAD1 FOREIGN KEY (ID_DLK_ORDER_HEAD) REFERENCES OD_ORDER_HEAD (ID_DLK_ORDER_HEAD) ON DELETE NO ACTION ON UPDATE NO ACTION',
  'SELECT ''skip_add_detail_fk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_brand_add := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD'
    AND CONSTRAINT_NAME = 'fk_OD_ORDER_HEAD_MD_BRAND1' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
  @fk_brand_add = 0,
  'ALTER TABLE OD_ORDER_HEAD ADD CONSTRAINT fk_OD_ORDER_HEAD_MD_BRAND1 FOREIGN KEY (ID_DLK_BRAND) REFERENCES MD_BRAND (ID_DLK_BRAND) ON DELETE NO ACTION ON UPDATE NO ACTION',
  'SELECT ''skip_add_brand_fk'' AS msg'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
