-- Archivo adjunto opcional en cabecera de orden (idempotente).
SET @db := DATABASE();

SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'NOM_ARCHIVO_ORDER_HEAD'
    ),
    'SELECT ''NOM_ARCHIVO_ORDER_HEAD ya existe'' AS msg',
    'ALTER TABLE OD_ORDER_HEAD ADD COLUMN NOM_ARCHIVO_ORDER_HEAD VARCHAR(255) NULL'
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := (
  SELECT IF(
    EXISTS(
      SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'OD_ORDER_HEAD' AND COLUMN_NAME = 'ARCHIVO_ORDER_HEAD'
    ),
    'SELECT ''ARCHIVO_ORDER_HEAD ya existe'' AS msg',
    'ALTER TABLE OD_ORDER_HEAD ADD COLUMN ARCHIVO_ORDER_HEAD MEDIUMBLOB NULL'
  )
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
