-- Flujo de suministro: reconstruir OD_ORDER_HEAD y OD_ORDER_DETAIL con los nuevos DDL.
-- Se descarta la data existente en ambas tablas (autorizado explícitamente por el usuario).
-- Cambios en OD_ORDER_HEAD: rename FEC_ENTRY → DATE_ENTRY, DATE_PROBABLE_DESPATCH → DATE_PROBABLE_DISPATCH,
-- FEC_PROCESO_* → FEH_PROCESO_*; se agregan FILE_SUPPLIES_UDP/PROD/FINAL + fechas.
-- Cambios en OD_ORDER_DETAIL: curva de tallas nueva (quita OS/1-2/2-3/4-5/13/15/XS/XXS,
-- agrega 0_3/3_6/0_6/6_12/12_18 y 3); separa IMG_ESTILO (imagen del estilo) de SUPPLY_FILE
-- (archivo de suministro del ítem); rename NOM_ESTILO → NAME_ESTILO, TOTAL_ESTILO → TOTAL_ORDER_PRODUCTION,
-- FEC_PROCESO_* → FEH_PROCESO_*.

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS OD_ORDER_DETAIL;
DROP TABLE IF EXISTS OD_ORDER_HEAD;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE OD_ORDER_HEAD (
  ID_DLK_ORDER_HEAD INT NOT NULL AUTO_INCREMENT COMMENT 'ID Unico de la Cabecera de la Orden de Pedido',
  ID_DLK_BRAND INT NOT NULL COMMENT 'Id Unico de la Marca',
  COD_ORDER_HEAD VARCHAR(100) NOT NULL COMMENT 'Codigo de la cabecera de la orden de pedido',
  QUANTITY_ORDER_HEAD INT NOT NULL COMMENT 'Cantidad total de prendas de la orden',
  DATE_ENTRY DATE NOT NULL COMMENT 'Fecha de ingreso de la orden',
  DATE_PROBABLE_DISPATCH DATE NOT NULL COMMENT 'Fecha estimada de despacho',
  FILE_ORDER_HEAD MEDIUMBLOB NULL COMMENT 'Archivo excel original de la orden',
  STAGE_ORDER_HEAD TINYINT(1) NULL COMMENT 'Etapa: 1=Registro, 2=Suministro, 3=Etiqueta, 4=Ruta, 5=Trazabilidad, 6=Lista negra',
  STATUS_STAGE_ORDER_HEAD TINYINT(1) NULL COMMENT 'Estado de la etapa: 1=Sin Iniciar, 2=Iniciado y 3=Concluido',
  FILE_SUPPLIES_UDP MEDIUMBLOB NULL COMMENT 'Excel Mapeo UDP',
  FEH_FILE_SUPPLIES_UDP DATE NULL,
  FILE_SUPPLIES_PROD MEDIUMBLOB NULL COMMENT 'Excel Mapeo Producción (con mermas)',
  FEH_FILE_SUPPLIES_PROD DATE NULL,
  FILE_SUPPLIES_FINAL MEDIUMBLOB NULL COMMENT 'Excel Consumo Final para Confección',
  FEH_FILE_SUPPLIES_FINAL DATE NULL,
  STATE_ORDER_HEAD TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Estado del registro: 1=Activo, 0=Inactivo',
  COD_USUARIO_CARGA_DL VARCHAR(20) NOT NULL COMMENT 'Usuario que cargó la orden',
  FEH_PROCESO_CARGA_DL DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Fecha de creación automática',
  FEH_PROCESO_MODIF_DL DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Fecha de modificación automática',
  DES_ACCION VARCHAR(20) NOT NULL COMMENT 'Descripción de acción: INSERT, UPDATE',
  FLG_STATUT_ACTIF TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Flag de estado del origen',
  PRIMARY KEY (ID_DLK_ORDER_HEAD),
  INDEX idx_order_head_brand (ID_DLK_BRAND ASC),
  CONSTRAINT fk_order_head_brand
    FOREIGN KEY (ID_DLK_BRAND)
    REFERENCES MD_BRAND (ID_DLK_BRAND)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE OD_ORDER_DETAIL (
  ID_DLK_ORDER_DETAIL INT NOT NULL AUTO_INCREMENT COMMENT 'Id Unico del detalle de la orden',
  ID_DLK_ORDER_HEAD INT NOT NULL COMMENT 'FK a OD_ORDER_HEAD',
  COD_ORDER_DETAIL VARCHAR(50) NULL COMMENT 'Codigo del detalle (Serialización)',
  COD_ESTILO VARCHAR(50) NULL COMMENT 'Codigo del estilo (Modelo)',
  NAME_ESTILO VARCHAR(200) NULL COMMENT 'Nombre del Estilo (Modelo)',
  IMG_ESTILO MEDIUMBLOB NULL COMMENT 'Imagen del estilo (Modelo)',
  DES_TELA VARCHAR(200) NULL COMMENT 'Nombre/Descripción de la tela',
  COLOR_AWAY VARCHAR(50) NULL COMMENT 'Color de lejos (Referencia visual)',
  FONDO_TELA VARCHAR(50) NULL COMMENT 'Fondo de tela',
  VERSION_TELA VARCHAR(50) NULL COMMENT 'Versión o variante de tela',
  ORDER_SAMPLE TINYINT(1) NULL DEFAULT 0 COMMENT '1 si es orden de muestra',
  SIZE_0_3 INT NULL DEFAULT 0,
  SIZE_3_6 INT NULL DEFAULT 0,
  SIZE_0_6 INT NULL DEFAULT 0,
  SIZE_6_12 INT NULL DEFAULT 0,
  SIZE_12_18 INT NULL DEFAULT 0,
  SIZE_2 INT NULL DEFAULT 0,
  SIZE_3 INT NULL DEFAULT 0,
  SIZE_4 INT NULL DEFAULT 0,
  SIZE_5 INT NULL DEFAULT 0,
  SIZE_6 INT NULL DEFAULT 0,
  SIZE_7 INT NULL DEFAULT 0,
  SIZE_8 INT NULL DEFAULT 0,
  SIZE_9 INT NULL DEFAULT 0,
  SIZE_10 INT NULL DEFAULT 0,
  SIZE_11 INT NULL DEFAULT 0,
  SIZE_12 INT NULL DEFAULT 0,
  SIZE_14 INT NULL DEFAULT 0,
  SIZE_16 INT NULL DEFAULT 0,
  SIZE_S INT NULL DEFAULT 0,
  SIZE_M INT NULL DEFAULT 0,
  SIZE_L INT NULL DEFAULT 0,
  SIZE_XL INT NULL DEFAULT 0,
  SIZE_XXL INT NULL DEFAULT 0,
  TOTAL_ORDER_PRODUCTION INT NULL COMMENT 'Suma total de tallas para este item',
  SUPPLY_FILE MEDIUMBLOB NULL COMMENT 'Archivo de suministros específico del item',
  STATE_ORDER_DETAIL TINYINT(1) NULL DEFAULT 1 COMMENT '1=Activo, 0=Inactivo',
  COD_USUARIO_CARGA_DL VARCHAR(20) NULL,
  FEH_PROCESO_CARGA_DL DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  FEH_PROCESO_MODIF_DL DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  DES_ACCION VARCHAR(20) NULL COMMENT 'INSERT, UPDATE',
  FLG_STATUT_ACTIF TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (ID_DLK_ORDER_DETAIL),
  INDEX idx_order_detail_head (ID_DLK_ORDER_HEAD),
  CONSTRAINT fk_detail_order_head
    FOREIGN KEY (ID_DLK_ORDER_HEAD)
    REFERENCES OD_ORDER_HEAD (ID_DLK_ORDER_HEAD)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
