-- Catálogo de MODELO (prendas) y tablas hijas.
-- Aditiva: 4 tablas nuevas, sin tocar tablas/datos existentes.
-- Imágenes como binario (MEDIUMBLOB), consistente con logos/IMG_ESTILO del resto del sistema.

CREATE TABLE `MD_MODEL` (
  `ID_DLK_MODEL`            INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_BRAND`           INT NOT NULL,
  `ID_DLK_SUBBRAND`        INT NULL,
  `COD_MODEL`              VARCHAR(50) NULL,
  `NAME_MODEL`             VARCHAR(100) NULL,
  `DES_MODEL`              VARCHAR(500) NULL,
  `NAME_COLLECTION`        VARCHAR(100) NULL,
  `DES_COLLECTION`         VARCHAR(500) NULL,
  `CATEGORY_MODEL`         VARCHAR(50) NULL,
  `MATERIAL_MODEL`         VARCHAR(200) NULL,
  `COMPOSITION_MODEL`      VARCHAR(200) NULL,
  `COLORWAY`               VARCHAR(50) NULL,
  `FONDO_TELA`             VARCHAR(50) NULL,
  `VERSION_TELA`           TINYINT NULL,
  `YEAR`                   SMALLINT NULL,
  `SEASON`                 VARCHAR(50) NULL,
  `SIZE_MODEL`             VARCHAR(50) NULL,
  `IS_SET`                 TINYINT NULL,
  `NRO_PIECES`             TINYINT UNSIGNED NULL,
  `CARE_MODEL`             VARCHAR(50) NULL,
  `TECHNICAL_SPECIFICATION` VARCHAR(100) NULL,
  `STATE_MODEL`            TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL`   VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL`   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`             VARCHAR(20) NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`       TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_MODEL`),
  INDEX `FK_MODEL_BRAND` (`ID_DLK_BRAND`),
  INDEX `FK_MODEL_SUBBRAND` (`ID_DLK_SUBBRAND`),
  CONSTRAINT `fk_model_brand`
    FOREIGN KEY (`ID_DLK_BRAND`) REFERENCES `MD_BRAND` (`ID_DLK_BRAND`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_model_subbrand`
    FOREIGN KEY (`ID_DLK_SUBBRAND`) REFERENCES `MD_SUBBRAND` (`ID_DLK_SUBBRAND`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MD_CARE` (
  `ID_DLK_CARE`          INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_MODEL`         INT NOT NULL,
  `COD_CARE`             VARCHAR(10) NOT NULL,
  `NOMB_CARE`            VARCHAR(50) NOT NULL,
  `CAR_DESCRIPTION`      VARCHAR(500) NOT NULL,
  `CAR_IMAGE`            MEDIUMBLOB NULL,
  `CAR_SAFETY`           VARCHAR(500) NULL,
  `STATE_CARE`           TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`           VARCHAR(20) NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`     TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_CARE`),
  INDEX `FK_CARE_MODEL` (`ID_DLK_MODEL`),
  CONSTRAINT `fk_care_model`
    FOREIGN KEY (`ID_DLK_MODEL`) REFERENCES `MD_MODEL` (`ID_DLK_MODEL`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MD_MODEL_IMAGES` (
  `ID_DLK_MODEL_IMAGES`  INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_MODEL`         INT NOT NULL,
  `IMAGE_DATA`           MEDIUMBLOB NOT NULL,
  `IMAGE_TYPE`           VARCHAR(30) NOT NULL,
  `STATE_IMAGE_MODEL`    TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`           VARCHAR(20) NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`     TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_MODEL_IMAGES`),
  INDEX `FK_MODEL_IMAGES_MODEL` (`ID_DLK_MODEL`),
  CONSTRAINT `fk_model_images_model`
    FOREIGN KEY (`ID_DLK_MODEL`) REFERENCES `MD_MODEL` (`ID_DLK_MODEL`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `MD_MODEL_DETAIL` (
  `ID_DLK_MODEL_DETAIL`  INT NOT NULL AUTO_INCREMENT,
  `ID_DLK_MODEL`         INT NOT NULL,
  `NAME_PIECE`           VARCHAR(100) NOT NULL,
  `STATE_MODEL_DETAIL`   TINYINT NOT NULL DEFAULT 1,
  `COD_USUARIO_CARGA_DL` VARCHAR(20) NOT NULL,
  `FEH_PROCESO_CARGA_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `FEH_PROCESO_MODIF_DL` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DES_ACCION`           VARCHAR(20) NULL DEFAULT 'INSERT',
  `FLG_STATUT_ACTIF`     TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_DLK_MODEL_DETAIL`),
  INDEX `FK_MODEL_DETAIL_MODEL` (`ID_DLK_MODEL`),
  CONSTRAINT `fk_model_detail_model`
    FOREIGN KEY (`ID_DLK_MODEL`) REFERENCES `MD_MODEL` (`ID_DLK_MODEL`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
