-- Etapa 3 (Etiqueta): tablas necesarias para emitir DPP por unidad serializada.
-- Crea MD_DIGITAL_IDENTIFIER (catálogo de identificadores físicos: NFC, QR, RFID, etc.),
-- OD_ORDER_LABEL_HEAD (cabecera por estilo dentro de la orden) y
-- OD_ORDER_LABEL_DETAIL (1 fila por unidad serializada con su sGTIN y URL DPP).
-- IS_BLACKLISTED en el detalle habilita la futura etapa 6 (Lista negra).

CREATE TABLE IF NOT EXISTS MD_DIGITAL_IDENTIFIER (
  ID_DLK_DIGITAL_IDENTIFIER INT NOT NULL AUTO_INCREMENT COMMENT 'Id Unico del identificador digital',
  COD_DIGITAL_IDENTIFIER VARCHAR(255) NOT NULL COMMENT 'Codigo único del identificador digital',
  TYPE_DIGITAL_IDENTIFIER VARCHAR(100) NULL COMMENT 'Tipo: NFC, QR, RFID, etc',
  MATERIAL_DIGITAL_IDENTIFIER VARCHAR(150) NULL COMMENT 'Material del soporte físico',
  LOCATION_DIGITAL_IDENTIFIER VARCHAR(255) NULL COMMENT 'Ubicación recomendada en la prenda',
  STANDARD_ISO_DIGITAL_IDENTIFIER VARCHAR(100) NULL COMMENT 'Estándar ISO aplicable',
  SUPPLIER_DIGITAL_IDENTIFIER VARCHAR(150) NULL COMMENT 'Proveedor del identificador',
  MODEL_DIGITAL_IDENTIFIER VARCHAR(150) NULL COMMENT 'Modelo / SKU del proveedor',
  SPECIFICATION_DIGITAL_IDENTIFIER MEDIUMBLOB NULL COMMENT 'Hoja técnica adjunta',
  OBSERVATION_DIGITAL_IDENTIFIER TEXT NULL,
  STATE_DIGITAL_IDENTIFIER TINYINT(1) NULL DEFAULT 1 COMMENT '1=Activo, 0=Inactivo',
  COD_USUARIO_CARGA_DL VARCHAR(20) NULL,
  FEH_PROCESO_CARGA_DL DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  FEH_PROCESO_MODIF_DL DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (ID_DLK_DIGITAL_IDENTIFIER),
  UNIQUE KEY idx_cod_digital_unique (COD_DIGITAL_IDENTIFIER)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OD_ORDER_LABEL_HEAD (
  ID_DLK_ORDER_LABEL_HEAD INT NOT NULL AUTO_INCREMENT COMMENT 'Id Unico de la cabecera de etiqueta',
  ID_DLK_ORDER_HEAD INT NOT NULL COMMENT 'FK a OD_ORDER_HEAD',
  ID_DLK_DIGITAL_IDENTIFIER INT NOT NULL COMMENT 'FK al catálogo MD_DIGITAL_IDENTIFIER',
  COD_ORDER_LABEL VARCHAR(20) NULL COMMENT 'Código corto de la cabecera de etiqueta',
  COD_ESTILO VARCHAR(50) NULL COMMENT 'Código del estilo asociado',
  NAME_ESTILO VARCHAR(200) NULL COMMENT 'Nombre del estilo',
  DESCRIPTION_ESTILO TEXT NULL,
  GENDER_ESTILO VARCHAR(45) NULL,
  SEASON_ESTILO VARCHAR(45) NULL,
  COD_GTIN VARCHAR(14) NULL COMMENT 'GTIN-14 base que se usa para los sGTIN',
  IDENTIFIER_TYPE VARCHAR(45) NULL COMMENT 'Tipo de identificador efectivo (snapshot)',
  IDENTIFIER_MATERIAL VARCHAR(500) NULL,
  IDENTIFIER_LOCATION VARCHAR(200) NULL,
  INICIO_SERIALIZACION INT NULL COMMENT 'Número inicial del rango serializado',
  FIN_SERIALIZACION INT NULL COMMENT 'Número final del rango serializado',
  TOTAL_LABEL INT NULL COMMENT 'Total de unidades serializadas (FIN - INICIO + 1)',
  SIGN_OPEN_RESPONSIBLE TEXT NULL COMMENT 'Firma de apertura (base64 o ref)',
  FEH_SIGN_OPEN DATETIME(3) NULL,
  SIGN_CLOSE_RESPONSIBLE TEXT NULL,
  FEH_SIGN_CLOSE DATETIME(3) NULL,
  DIGITAL_CERTIFICATE_ID VARCHAR(100) NULL,
  STATE_ORDER_LABEL_HEAD TINYINT(1) NULL DEFAULT 1 COMMENT '1=Activo, 0=Inactivo',
  COD_USUARIO_CARGA_DL VARCHAR(20) NULL,
  FEH_PROCESO_CARGA_DL DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  FEH_PROCESO_MODIF_DL DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  DES_ACCION VARCHAR(20) NULL,
  FLG_STATUT_ACTIF TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (ID_DLK_ORDER_LABEL_HEAD),
  INDEX idx_label_head_order (ID_DLK_ORDER_HEAD),
  INDEX idx_label_head_digital_id (ID_DLK_DIGITAL_IDENTIFIER),
  CONSTRAINT fk_label_head_order
    FOREIGN KEY (ID_DLK_ORDER_HEAD)
    REFERENCES OD_ORDER_HEAD (ID_DLK_ORDER_HEAD)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_label_head_digital_master
    FOREIGN KEY (ID_DLK_DIGITAL_IDENTIFIER)
    REFERENCES MD_DIGITAL_IDENTIFIER (ID_DLK_DIGITAL_IDENTIFIER)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OD_ORDER_LABEL_DETAIL (
  ID_DLK_ORDER_LABEL_DETAIL INT NOT NULL AUTO_INCREMENT COMMENT 'Id Unico del detalle de etiqueta',
  ID_DLK_ORDER_LABEL_HEAD INT NOT NULL COMMENT 'FK a OD_ORDER_LABEL_HEAD',
  ITEM_GLOBAL INT NOT NULL COMMENT 'Número correlativo dentro de la orden',
  ITEM_BY_SIZE INT NOT NULL COMMENT 'Número correlativo dentro de la talla',
  SERIAL_NUMBER VARCHAR(20) NOT NULL COMMENT 'Serial dentro del rango (parte del sGTIN)',
  SGTIN_FULL VARCHAR(150) NOT NULL COMMENT 'sGTIN completo (urn:epc:id:sgtin)',
  URL_DPP_FULL VARCHAR(1000) NOT NULL COMMENT 'URL pública del DPP',
  COLOR VARCHAR(100) NULL,
  PRINT VARCHAR(100) NULL,
  SIZE VARCHAR(50) NULL,
  IS_BLACKLISTED TINYINT(1) NULL DEFAULT 0 COMMENT '1 si la unidad fue bloqueada (lista negra)',
  REASON_BLACKLIST VARCHAR(100) NULL,
  STATE_ORDER_LABEL_DETAIL TINYINT(1) NULL DEFAULT 1,
  FEH_PROCESO_CARGA_DL DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  FEH_PROCESO_MODIF_DL DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  COD_USUARIO_AUDITOR VARCHAR(20) NULL,
  PRIMARY KEY (ID_DLK_ORDER_LABEL_DETAIL),
  UNIQUE KEY idx_sgtin_unique (SGTIN_FULL),
  INDEX idx_label_detail_head (ID_DLK_ORDER_LABEL_HEAD),
  INDEX idx_quality_control (IS_BLACKLISTED),
  CONSTRAINT fk_label_detail_to_head
    FOREIGN KEY (ID_DLK_ORDER_LABEL_HEAD)
    REFERENCES OD_ORDER_LABEL_HEAD (ID_DLK_ORDER_LABEL_HEAD)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
