-- Etapa 3 (Etiqueta) — soporte de colorway, estampado y SETS.
-- Aplicar a local y prod. Idempotente. No destructivo: solo agrega columnas/FK.
--
-- OD_ORDER_DETAIL    : ES_SET / NUM_PIEZAS  -> marca si la orden de producción es un set.
-- OD_ORDER_LABEL_HEAD: ID_DLK_ORDER_DETAIL  -> enlaza la cabecera al colorway exacto.
--                      ESTAMPADO            -> estampado del modelo/colorway.
-- OD_ORDER_LABEL_DETAIL: PIECE_TYPE / SET_GROUP_ID -> pieza del set y agrupación.

-- ── OD_ORDER_DETAIL.ES_SET ───────────────────────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_DETAIL' AND COLUMN_NAME='ES_SET');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_DETAIL ADD COLUMN ES_SET TINYINT(1) NOT NULL DEFAULT 0 COMMENT ''1=la orden de producción es un set'' AFTER TOTAL_ORDER_PRODUCTION',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── OD_ORDER_DETAIL.NUM_PIEZAS ───────────────────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_DETAIL' AND COLUMN_NAME='NUM_PIEZAS');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_DETAIL ADD COLUMN NUM_PIEZAS INT NOT NULL DEFAULT 1 COMMENT ''Piezas por unidad (2 = pijama pantalón+camisa)'' AFTER ES_SET',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_DETAIL ──────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_LABEL_HEAD' AND COLUMN_NAME='ID_DLK_ORDER_DETAIL');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_LABEL_HEAD ADD COLUMN ID_DLK_ORDER_DETAIL INT NULL COMMENT ''FK al colorway (OD_ORDER_DETAIL)'' AFTER ID_DLK_DIGITAL_IDENTIFIER',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── OD_ORDER_LABEL_HEAD.ESTAMPADO ────────────────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_LABEL_HEAD' AND COLUMN_NAME='ESTAMPADO');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_LABEL_HEAD ADD COLUMN ESTAMPADO VARCHAR(100) NULL COMMENT ''Estampado del modelo/colorway'' AFTER COD_GTIN',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── FK OD_ORDER_LABEL_HEAD.ID_DLK_ORDER_DETAIL -> OD_ORDER_DETAIL ─────
SET @fk := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_LABEL_HEAD'
    AND CONSTRAINT_NAME='fk_label_head_order_detail');
SET @sql := IF(@fk=0,
  'ALTER TABLE OD_ORDER_LABEL_HEAD ADD CONSTRAINT fk_label_head_order_detail FOREIGN KEY (ID_DLK_ORDER_DETAIL) REFERENCES OD_ORDER_DETAIL (ID_DLK_ORDER_DETAIL) ON DELETE RESTRICT ON UPDATE CASCADE',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── OD_ORDER_LABEL_DETAIL.PIECE_TYPE ─────────────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_LABEL_DETAIL' AND COLUMN_NAME='PIECE_TYPE');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_LABEL_DETAIL ADD COLUMN PIECE_TYPE VARCHAR(45) NULL COMMENT ''Pieza del set: PANTALON, CAMISA, etc. NULL=prenda simple'' AFTER SIZE',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- ── OD_ORDER_LABEL_DETAIL.SET_GROUP_ID ───────────────────────────────
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='OD_ORDER_LABEL_DETAIL' AND COLUMN_NAME='SET_GROUP_ID');
SET @sql := IF(@col=0,
  'ALTER TABLE OD_ORDER_LABEL_DETAIL ADD COLUMN SET_GROUP_ID VARCHAR(50) NULL COMMENT ''Agrupa las piezas del mismo set físico'' AFTER PIECE_TYPE',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
