-- MD_MATERIAL: campos de pedido (orden, color, rollo, factura).
-- Idempotente. Aplicar a local y prod.
-- Cada columna se agrega solo si no existe (evita error al re-ejecutar).

-- ORDER_FORM
SET @col_exists := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'MD_MATERIAL'
    AND COLUMN_NAME = 'ORDER_FORM'
);
SET @sql := IF(@col_exists = 0,
  'ALTER TABLE MD_MATERIAL ADD COLUMN ORDER_FORM VARCHAR(20) NULL COMMENT ''Orden del Pedido para el cual se requiere el material'' AFTER CERTIFICATION',
  'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- COLOR_MATERIAL
SET @col_exists := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'MD_MATERIAL'
    AND COLUMN_NAME = 'COLOR_MATERIAL'
);
SET @sql := IF(@col_exists = 0,
  'ALTER TABLE MD_MATERIAL ADD COLUMN COLOR_MATERIAL VARCHAR(100) NULL COMMENT ''Color del material'' AFTER ORDER_FORM',
  'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ROLL_MATERIAL
SET @col_exists := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'MD_MATERIAL'
    AND COLUMN_NAME = 'ROLL_MATERIAL'
);
SET @sql := IF(@col_exists = 0,
  'ALTER TABLE MD_MATERIAL ADD COLUMN ROLL_MATERIAL VARCHAR(45) NULL COMMENT ''Rollo del material, ejemplo: Codigo del rollo de tela'' AFTER COLOR_MATERIAL',
  'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- INVOICE_MATERIAL
SET @col_exists := (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'MD_MATERIAL'
    AND COLUMN_NAME = 'INVOICE_MATERIAL'
);
SET @sql := IF(@col_exists = 0,
  'ALTER TABLE MD_MATERIAL ADD COLUMN INVOICE_MATERIAL VARCHAR(45) NULL COMMENT ''Factura del material'' AFTER ROLL_MATERIAL',
  'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
