-- LG_USER_ACCESS: nuevo schema con ENUMs y precisión a milisegundos.
-- Idempotente: borra la tabla si existe y la crea con el esquema final.
-- Ejecutar en local Y en prod.

DROP TABLE IF EXISTS LG_USER_ACCESS;

CREATE TABLE LG_USER_ACCESS (
  ID_LOG_ACCESS    BIGINT       NOT NULL AUTO_INCREMENT,
  ID_DLK_USER_REO  INT          NOT NULL,
  IP_ADDRESS       VARCHAR(45)  NOT NULL,
  BROWSER          VARCHAR(50)  NULL DEFAULT NULL,
  BROWSER_VERSION  VARCHAR(50)  NULL DEFAULT NULL,
  OPERATING_SYSTEM VARCHAR(50)  NULL DEFAULT NULL,
  DEVICE_TYPE      ENUM('PC','MOBILE','TABLET','BOT','OTHER') NOT NULL DEFAULT 'PC',
  LATITUDE         DECIMAL(10,8) NULL DEFAULT NULL,
  LONGITUDE        DECIMAL(11,8) NULL DEFAULT NULL,
  CITY             VARCHAR(100) NULL DEFAULT NULL,
  COUNTRY          VARCHAR(100) NULL DEFAULT NULL,
  ACCESS_STATUS    ENUM('SUCCESS','FAILED','BLOCKED','PENDING') NOT NULL,
  FEH_ACCESS       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  USER_AGENT_RAW   TEXT         NULL DEFAULT NULL,
  PRIMARY KEY (ID_LOG_ACCESS),
  CONSTRAINT LG_USER_ACCESS_ID_DLK_USER_REO_fkey
    FOREIGN KEY (ID_DLK_USER_REO)
    REFERENCES MD_USER_REO (ID_DLK_USER_REO)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
